### ISSUE TITLE
(Solved) Need such rule whose domain name is took placed by a wildcard character

### ISSUE THREAD

**Issue by 3-2** [iorate/uBlacklist#101]
\*://\*.\*.com/key/\*
I want to block the above URL pattern which doesn't have a definite domain name. I also tried regular expression but failed again.
/.\*\.com\/key\/.\*

The motive I need to do this is for blocking those mass Content Farm websites which all redirect to tspweb.com eventually. You may have a look by search '随机推荐 site:*.com/key' on Google (without quotation marks). All the results will redirect to a same content farm website.

Update:
I solved it by myself, the right URL pattern is:
\*://\*/key/\*.html

Translation for Chinese users:
屏蔽不包含确定域名的链接格式

我想屏蔽这样的链接格式，不包含确定的域名：
\*://\*.\*.com/key/\*
我也试了正则表达式，但还是不行：
/.\*\.com\/key\/.\*
我之所以想这样做是为了屏蔽大量的内容农场网站，他们全都最终重定向到同一个内容农场网站 tspweb.com
你可以通过谷歌搜索“随机推荐 site:*.com/key”来看一下。所有的结果都会重定向到一个相同的内容农场网站。

更新：
我自己解决了。正确的 URL 格式是：
\*://\*/key/\*.html

**Comment by silentbrains** [comment]
What about `/.+\.com\/key/` ? Need to escape the dot and backslash.

**Comment by 3-2** [comment]
> What about `/.+\.com\/key/` ? Need to escape the dot and forward-slash.
@silentbrains 
I tried your
/.+\\.com\\/key\\/.*
but still doesn't work.
(I confirmed this rule in [regular expression 101](https://regex101.com/) for the links from those [search results](https://www.google.com/search?q=%E9%9A%8F%E6%9C%BA%E6%8E%A8%E8%8D%90+site%3A*.com%2Fkey), which all matched successfully.)

HOWEVER, I succeeded with this rule:
\*://\*/key/\*
Wow!
After the failure just now I clicked the [Match Patterns](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns) in the option page of this extension and carefully read this document then found the right URL pattern!
OK, the problem is solved.

NOTE: For blocking this content farm website more precisely in case accidentally blocking good websites, the definitive URL pattern is:
*://*/key/*.html

**Comment by iorate** [comment]
> I tried your
/.+\.com\/key\/.*
but still doesn't work.

Regular expression literals should be closed with `/`: `/.+\.com\/key\/.*/`
More simply: `/\.com\/key\//`

> HOWEVER, I succeeded with this rule:
*://*/key/*

That's good.
To block domains on `.com` only: `*://*.com/key/*`
