### ISSUE TITLE
Feature request: Make it easier to report spam sites to search engine

### ISSUE THREAD

**Issue by teohhanhui** [iorate/uBlacklist#109]
It should be possible to pre-fill the form, e.g. https://developers.google.com/search/docs/advanced/guidelines/report-spam

**Comment by iorate** [comment]
That feature will never be implemented because I believe it deviates from the main functionality of this extension.
It should be implemented in other extensions.

**Comment by teohhanhui** [comment]
So we'll continue pouring glasses of water at a raging fire.

It's unfortunate that we're even in this situation in the first place. Having all the users report those sites would certainly help to turn the tide, no?
