### ISSUE TITLE
[Firefox for Android] Unable to add subscription

### ISSUE THREAD

**Issue by teohhanhui** [iorate/uBlacklist#110]
## Expected Behavior
The prompt to request for permissions (e.g. raw.githubusercontent.com) should show up.

## Actual Behavior
Nothing happens. It seems like the request for permissions is broken? (Same problem when clicking "Enable" for Bing, DuckDuckGo, etc.)

## Steps to Reproduce the Problem

1. Go to the "Options" page.
2. Click the "Add a subscription" button.
3. Fill in the name and URL.
4. Click the "Add" button.

## Specifications

- OS: Android 11
- Browser: Firefox for Android (Firefox Nightly 93.0a1)
- Other extensions that might interfere: N/A

**Comment by alieren34** [comment]
As I guess, you need to use Firefox 78 or a previous version in order to use uBlackList properly.

**Comment by teohhanhui** [comment]
> As I guess, you need to use Firefox 78 or a previous version in order to use uBlackList properly.

Fenix supports WebExtensions. I'm using Nightly so I can use a custom collection. It should be possible to fix Fenix support in uBlacklist, unless there's a missing API that's required.

**Comment by iorate** [comment]
`permissions.request`, the API to dynamically request permissions,  seems to be not yet implemented in Fenix.
https://github.com/mozilla-mobile/fenix/issues/16912
https://bugzilla.mozilla.org/show_bug.cgi?id=1601420

Actually, permission requests are not always necessary for subscription. When the server accepts CORS requests from the origin of this extension, no permission for the origin of the server is required. In particular, `raw.githubusercontent.com`.
A workaround is to add a checkbox to ask whether to request a permission to the dialog to add subscription.

**Comment by iorate** [comment]
This problem should be partially resolved in v6.3.0. In this version, the second workaround above is introduced; permission request for `*.githubusercontent.com` is omitted.
For further problems on Firefox for Android, please move to #117 .
