### ISSUE TITLE
Add ability to "hide" the extension link under drop-down menu

### ISSUE THREAD

**Issue by AlexWayfer** [iorate/uBlacklist#112]
Hello!

Thank you for such great extension.

There is only wish to have the link not near each result for every search, but (as I use it rarely) have an ability to block, but hidden.

![2021-08-25_17-42](https://user-images.githubusercontent.com/6510020/130811991-ba6545b9-7bd9-4c1b-9a4e-1ab2784a4a6f.png)

**Comment by iorate** [comment]
I don't think it is a very good idea but pull requests are of course welcome.

You can configure this extension to *always* hide the links in the options page.

![block-links](https://user-images.githubusercontent.com/682043/131243188-b96622d0-e951-4e0b-aa00-7c88f172c7eb.png)
