### ISSUE TITLE
Chrome extension is blocked. How install it?

### ISSUE THREAD

**Issue by Nashev** [iorate/uBlacklist#114]
https://chrome.google.com/webstore/detail/ublacklist/pncfbmialoiaghdehhbnbhkkgmjanfhe - does not allow to install (((

Could You please describe an alternative way to install it in a readme file?

**Comment by iorate** [comment]
This extension does not restrict who can use it, so the problem is probably dependent on your environment. However, you wrote nothing about your environment and the details of "does not allow to install".
