### ISSUE TITLE
Wrong behavior ?

### ISSUE THREAD

**Issue by universalbyte** [iorate/uBlacklist#116]
## Expected Behavior
ASTERISK://ASTERISK.example.com/*
ASTERISK://ASTERISK.mozilla.org/*
## Actual Behavior
ASTERISK://www.example.com/*
ASTERISK://www.mozilla.org/*
## Steps to Reproduce the Problem

1.Open www.example.com or www.mozilla.org
1.Click on uBlacklist
1.Block

## Specifications

- OS:Gnu/Linux
- Browser:firefox-91.0.2.tar.bz2, uBlacklist-v6.3.1
- Other extensions that might interfere:None

INFO: Sorry, Github removed some *(asterisk)

**Comment by iorate** [comment]
It is the intended behavior.
See also: #83
