### ISSUE TITLE
Add support for Firefox for Android

### ISSUE THREAD

**Issue by iorate** [iorate/ublacklist#117]
For now, this extension cannot be installed to the stable version of Firefox for Android.
> Currently, only a limited number of extensions in our Recommended program are supported on the new Firefox for Android (codename: Fenix) release channel.

https://blog.mozilla.org/addons/2020/02/11/faq-for-extension-support-in-new-firefox-for-android/

Advanced users can install this extension to Firefox for Android *Nightly* according to:
https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

However, "Other search engines" and "Subscription" are not currently available in Firefox for Android Nightly because `browser.permissions.request`, which is the API to dynamically request permissions, is not yet implemented in GeckoView:
mozilla-mobile/fenix#16912
https://bugzilla.mozilla.org/show_bug.cgi?id=1601420

Exceptionally, subscriptions to blocklists hosted on `*.githubusercontent.com` may be available because permission request for this origin is omitted. re #110

**Comment by yan12125** [comment]
> Exceptionally, subscriptions to blocklists hosted on *.githubusercontent.com may be available because permission request for this origin is omitted. re #110

Thanks a lot for this workaround! Would you accept more such domains? I'd like to subscribe to lists on GitLab. Although GitLab itself [does not use `
Access-Control-Allow-Origin: *`](https://gitlab.com/gitlab-org/gitlab/-/issues/16732), some third-party CDN services do:

* GitHack: using domain `glcdn.githack.com` for files on GitLab
* Statically: using domain `cdn.statically.io`

**Comment by iorate** [comment]
@yan12125 
Thank you for your suggestion. You might want to create a pull request. The code to change:
https://github.com/iorate/uBlacklist/blob/bbc2d22a24b04cf04ac4caced1d470876da355d8/src/scripts/options/subscription-section.tsx#L53

**Comment by yan12125** [comment]
Thanks! Let me try it out.

**Comment by iorate** [comment]
Sync is not available in Firefox for Android (Fenix) now because `browser.identity.launchWebAuthFlow` is not implemented.

Recently I added support for sync in Safari. Because Safari also lacks `browser.identity.launchWebAuthFlow`, I implemented an alternative to it. Is that alternative available in Fenix? Currently, no. It requires `browser.permissions.request`, which is not yet implemented in Fenix.

**Comment by yan12125** [comment]
I think this issue should remain open even without activity?

**Comment by iorate** [comment]
I added a label that is exempt from stale

**Comment by Semro** [comment]
According to https://bugzilla.mozilla.org/show_bug.cgi?id=1601420 `browser.permissions.request` is implemented.

**Comment by iorate** [comment]
I tried uBlacklist 7.6.0 on Firefox Nightly 103, but no permission prompt showed.
Maybe we need to wait for an update of Fenix.
https://github.com/mozilla-mobile/fenix/issues/16912

**Comment by item4** [comment]
any update more?

**Comment by 3xploiton3** [comment]
Please support kiwi browser too

**Comment by amroncz** [comment]
Is there an update for this?
I can't activate UBlacklist on Android from the Firefox Add-On Store in Firefox / Firefox Nightly, nor from the Chrome Web Store in Kiwi.
Is there a workaround to use UBlacklist on Android?

**Comment by teohhanhui** [comment]
> I can't activate UBlacklist on Android from the Firefox Add-On Store in Firefox / Firefox Nightly

You need to use Firefox Beta or Firefox Nightly, and follow these instructions: https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

**Comment by amroncz** [comment]
> > However, it only works in the news tab as long as the checkmark for desktop view is checked in Firefox.
> 
> Works for me on Firefox Beta for Android. (I'm also using Google Search Fixer to bypass the browser discrimination.)

I have edited my previous post. The problem occurs only in the news tab. Here it works only in desktop view mode.

**Comment by Eagle-85** [comment]
uBlackList V8.3.1 is working great for Google Search with Firefox Beta 117.0b4.  
It is not working for other search engines for me.  
In Options, Other Search Engines, the Enable button does not work if any other search engine is checked.

**Comment by teohhanhui** [comment]
> but no permission prompt showed

Looks like it should be released in Firefox 120: https://github.com/mozilla-mobile/firefox-android/pull/3917

**Comment by NotaInutilis** [comment]
It works now! https://www.mozilla.org/en-US/firefox/android/120.0/releasenotes/
I was able to install the extension directly from the firefox addon page. Although the mobile search is still limited to officially endorsed addons, accessing the page directly allows to click and install it.
Not sure if the rollout is the same for everyone though.

**Comment by iorate** [comment]
I'm closing this issue because we can now install this add-on to Firefox for Android 120.0 (or later).
For further problems with Firefox for Android, please create a separate issue for each problem.
