### ISSUE TITLE
[Firefox] It stopeed working after the latest update

### ISSUE THREAD

**Issue by 17721** [iorate/uBlacklist#12]
Please, update the plugin, because it doesn't work anymore and don't hide search results from appearance.

**Comment by iorate** [comment]
It may be a Firefox bug.
https://support.mozilla.org/en-US/kb/add-ons-disabled-or-fail-to-install-firefox
https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/
Please try to update Firefox.

**Comment by 17721** [comment]
It's up-to-date (v 66.0.5) as well as the plugin (May 11th), yet it's still don't hide blocked websites from search results and they're highlighted in red color instead. 

https://i.ibb.co/d6sqjNX/Untitled.jpg

**Comment by iorate** [comment]
Does that problem occur when all your other extensions are disabled?

**Comment by 17721** [comment]
> 
> 
> Does that problem occur when all your other extensions are disabled?

I found that troublesome plugin:
https://addons.mozilla.org/en-US/firefox/addon/css-exfil-protection/

The problem is gone. Thanks!
