### ISSUE TITLE
Not working after upgrading to v6.3.6.

### ISSUE THREAD

**Issue by Slaier** [iorate/uBlacklist#122]
## Expected Behavior

Work as normal as v6.3.5.

## Actual Behavior

cannot add subscriptions or match patterns.

## Steps to Reproduce the Problem

1. Add a subscription

## Specifications

- OS: NixOS 21.05 (Okapi) x86_64
- Browser: Firefox
- uBlacklist Version: v6.3.6

**Comment by iorate** [comment]
what version of firefox do you use?

**Comment by Slaier** [comment]
78.14.0esr (64-bit)

**Comment by iorate** [comment]
Upgrading of the build system may have broken support for old browsers.
To be honest, I don't want to care about old browsers. The latest version of Firefox ESR is 91.

You have 2 options:
- create a pull request to support Firefox 78 ESR
- use the latest version of Firefox ESR (I know nothing about NixOS, but there seems to be [a package of ESR 91](https://search.nixos.org/packages?channel=21.05&show=firefox-esr-91&from=0&size=15&sort=relevance&type=packages&query=firefox))
