### ISSUE TITLE
Why can't we simply filter the sites and ALL domain variants?

### ISSUE THREAD

**Issue by elcosomalo1** [iorate/uBlacklist#128]
## Expected Behavior
Be able to use an * to filter a determined website and all its domain variants
```
e.g: *://*.*.softonic.com/*
e.g: *://*.softonic.*/*
```

## Actual Behavior
The extension only blocks one specific site, all the other diferent domains are shown.
```
e.g:   *://*.en.softonic.com/* is blocked
         www.es.softonic.com is shown in results
or
        *://*.softonic.com/* is blocked
        www.softonic.es is shown in results
```

## Specifications

- OS: Windows 10
- Browser: Edge
- Other extensions that might interfere:

![image](https://user-images.githubusercontent.com/43975882/134785822-043be8a4-62e5-40b8-aa14-869bcca09ff1.png)
![image](https://user-images.githubusercontent.com/43975882/134785847-9fd3db7d-7b9a-464c-868c-c0ade31848e3.png)

**Comment by iorate** [comment]
That is the specification of [match patterns](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns). Use regular expressions instead.

To block softonic, for example, simply add
```
/\.softonic\./
```

**Comment by 07416** [comment]
> That is the specification of [match patterns](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns). Use regular expressions instead.
> 
> To block softonic, for example, simply add
> 
> ```
> /\.softonic\./
> ```

`.com.au` domains seem unadressed — for instance `/\.bestbuy\./` doesn't block `https://bestbuy.com.au/`

Would be nice to know one regex string to 100% block `.domain.` !
