### ISSUE TITLE
Feature request: block search results by title, not only URL

### ISSUE THREAD

**Issue by 3-2** [iorate/uBlacklist#129]
Recently I found some spamdexing websites appeared among the search results. They have irregular URL but regular title.
If any substring in the title of a search result matches the string I added into the list beforehand, this result will be blocked. 
This is the feature I want and I believe it must be very helpful to users.

**Comment by iorate** [comment]
It's already implemented.
See the options page or [here](https://iorate.github.io/ublacklist/advanced-features#regular-expressions-for-page-titles).
