### ISSUE TITLE
Suggestion: Donation options?

### ISSUE THREAD

**Issue by KI5JYD** [iorate/uBlacklist#13]
OK, not really a bug, but a suggestion. 

My issue is: A developer's gotta eat! ;)

I am stoked that @iorate brought back this extension for Google Chrome (my *sometimes* default browser) in which the "official" Google extension just stopped working. (I left a review of the extension on the Chrome Web Store BTW).

But development, as it is usually said, a thankless job. I think iorate needs some kind of encouragement, by maybe donations like PayPal, Patreon, Bitcoin, whatever. 

I'd like to suggest this. It's a great idea, and I like to thank @iorate for making **my** life easier by doing the right thing, and that's by donating a little bit to keep development going.

73, KI5JYD

**Comment by iorate** [comment]
I appreciate your kindness, but I have no plan to add donation options. 

I develop this extension just because I need it. As long as I am a user of Google Search, I will probably continue to maintain it.
