### ISSUE TITLE
uBlacklist doesn't work well with Greasemonkey script “endless google” 

### ISSUE THREAD

**Issue by xuyangmvp** [iorate/uBlacklist#134]
## Expected Behavior
The Greasemonkey script “endless google” loads more search result pages automatically when scroll down at the google text search page.
uBlacklist block specific sites on the automatically loaded pages.

## Actual Behavior
uBlacklist does not block specific sites on the automatically loaded pages.

## Steps to Reproduce the Problem

1. Install the userscript manager [Tampermonkey ](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo) and theGreasemonkey script [“endless google”](https://openuserjs.org/scripts/tumpio/Endless_Google)
1. Perform a google text search that yields a large quantity of filtered results.
1. Scroll down to the end of first page, "endless google" automatically loads the next page.
1.  uBlacklist doesn't block specific sites on the next page.

## Specifications

- OS: Win10
- Browser: Chrome
- Other extensions that might interfere:

**Comment by iorate** [comment]
dup #59 #65 #86

I'm not going to support all other extensions/userscripts that modify Google search result pages, although pull requests are welcome.
My recommendation is [uAutoPagerize](https://chrome.google.com/webstore/detail/uautopagerize/kdplapeciagkkjoignnkfpbfkebcfbpb?hl=en). It works great with uBlacklist.
