### ISSUE TITLE
Compact with preloader

### ISSUE THREAD

**Issue by ykrank** [iorate/uBlacklist#136]
## Expected Behavior
When i use tampermonkey script (like https://greasyfork.org/zh-CN/scripts/33522-super-preloaderplus-one-new) to preload google search result, i expected all result is filter by uBlacklist.
## Actual Behavior
the first page is filter by uBlacklist, but others is origin result.
## Steps to Reproduce the Problem

1. install uBlacklist and add block rule
2. install tampermonkey
3. install https://greasyfork.org/zh-CN/scripts/33522-super-preloaderplus-one-new in tampermonkey
4. search google

**Comment by iorate** [comment]
dup #59 #65 #86 #134

I'm not going to support all other extensions/userscripts that modify Google search result pages, although pull requests are welcome.
