### ISSUE TITLE
Invalid in a specific Chromium version.

### ISSUE THREAD

**Issue by YamatoRyou** [iorate/uBlacklist#141]
## Expected Behavior
n/a

## Actual Behavior
It does not take effect in a specific Chromium version. It has been determined that it is not a rule grammatical error, because the same rules behave normally in Chrome 94/95. When uBlacklist rolls back to 6.8.1, the extension will take effect.

## Steps to Reproduce the Problem
n/a

## Specifications
- uBlacklist: 6.8.2 or higher
- OS: x64 Windows 7
- Browser: Cent Browser 4.3.9.248 (**Chromium 86.0.4240.198**), x64
- Other extensions that might interfere: n/a

**Comment by iorate** [comment]
dup #139 
Use the latest version of Chromium (at least 88) or enable chrome://flags/#enable-experimental-web-platform-features.
