### ISSUE TITLE
Update privacy practices on Chrome Web Store

### ISSUE THREAD

**Issue by malcolmmurphy** [iorate/uBlacklist#142]
On the Chrome web store page for uBlacklist: https://chrome.google.com/webstore/detail/ublacklist/pncfbmialoiaghdehhbnbhkkgmjanfhe/related?hl=en

Under "Privacy practices" there is the following statement:
> **uBlacklist collects the following:**
> ### Authentication information
> For example: passwords, credentials, security question, or personal identification number (PIN)

I assume this is related to having the sync option? Both Google Drive and Dropbox appear to be accessed via OAuth, so is this statement really needed? Perhaps related to a method in the past? Or is the statement about something else entirely? Regardless I think it might be deterring users (I personally had to do a quick scan of the source before feeling comfortable using it). Just a suggestion. Extension looks amazing BTW, I'm looking forward to putting it to use... probably starting with Pinterest as that comes to mind first. Cheers!

**Comment by iorate** [comment]
@malcolmmurphy 
Sorry for my late response.
Your interpretation seems right to me.
I just asked a question on the official forum just to be sure.
https://groups.google.com/u/2/a/chromium.org/g/chromium-extensions/c/g5nHYhQNz8Q

**Comment by iorate** [comment]
No answer yet, but I will remove the declaration that this extension collects authentication information in the next release.
