### ISSUE TITLE
Extension does not work when visiting bing.com on iPhone

### ISSUE THREAD

**Issue by HoneyLuka** [iorate/uBlacklist#144]
![image](https://user-images.githubusercontent.com/4635725/140177467-5e52ef66-a696-45cd-bd88-ebe34ffe4eda.png)

From user report. I reproduced it. It seems only not working on bing.com mobile website with iPhone. When I use iPad it’s working properly. 

I guess it might be a code change on bing.com.

**Comment by iorate** [comment]
I just added support for Bing on iPhone.

<img alt="bing" src="https://user-images.githubusercontent.com/682043/140641208-86aa0e84-310a-4047-9afb-54cd35045fc4.png" width="400px">

NOTE: This extension does not block ads. To block ads, use a content blocker.

**Comment by HoneyLuka** [comment]
Thank you for your work❤️
