### ISSUE TITLE
Not found in Extensions of MacOS 12.0.1 Safari

### ISSUE THREAD

**Issue by ericcug** [iorate/uBlacklist#145]
## Expected Behavior

Should it be enabled in Safari -> Preferences-> Extensions

## Actual Behavior

Not found in Extension after upgrade to MacOS Monterey 12.0.1

## Steps to Reproduce the Problem

1.Install from Mac App Store
2.Open Safari -> Preferences -> Extensions
3.Not found uBlacklist for Safari

## Specifications

- OS:MacOS Monterey 12.0.1
- Browser:Safari 15.1

**Comment by HoneyLuka** [comment]
The problem doesn't seem to be with uBlacklist itself.
You can try this:
1. Run this in the terminal app: /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user
2. Restart Safari
3. Enable uBlacklist

ref: https://github.com/bitwarden/desktop/issues/1126#issuecomment-955763402

Please let me know if your problem resolved.

**Comment by ericcug** [comment]
Thanks @HoneyLuka . It Works!

**Comment by HoneyLuka** [comment]
Glad to see that your problem is solved. 
Some users are also reporting the same problem. I've put this workaround in the changelog of the new app store version

**Comment by iorate** [comment]
I've checked the workaround described in the changelog and so will close this issue.
