### ISSUE TITLE
How to highlight a website in the search results?

### ISSUE THREAD

**Issue by iaeiou** [iorate/uBlacklist#151]
Hi there,

## Expected Behavior

I'm trying to highlight a website in the search results

## Actual Behavior

According to [this issue](https://github.com/iorate/uBlacklist/issues/150), the regex `@*://stackoverflow.com/*` should work, but it's not accepted (the "Block" button is blurred as soon as I add an `@`).

## Steps to Reproduce the Problem

- Go to google and search something
- Select a result and click on "Block this site"
- Add an `@` at the beginning of the regex, or `@1`

The "Block" button is blurred and the rule cannot be added.

## Specifications

- OS: Debian 10
- Browser: Firefox 78.15.0esr  and Firefox 95.0b12 
- Other extensions that might interfere: None (Reproduced on a clean install with no other extensions)

Thanks for this awesome extension!

**Comment by iorate** [comment]
Add a rule `@1*://stackoverflow.com/*` *in the options page*.
