### ISSUE TITLE
googel  search results no black Button and *://www.muzijie.com/*   Not blocked

### ISSUE THREAD

**Issue by xianren2021** [iorate/ublacklist#152]
![2021-12-03_005148](https://user-images.githubusercontent.com/95434795/144467581-5c9ada7f-8f58-4e0d-a553-fecabf619db1.png)

![2021-12-03_005235](https://user-images.githubusercontent.com/95434795/144467810-7901f997-eeca-4d7e-9585-94143d577345.png)

![2021-12-03_005614](https://user-images.githubusercontent.com/95434795/144467830-48a76a0c-7e32-4639-ac50-52182b45da1d.png)

- OS:windows10 64
- ublacklist 6.12.0
- Browser:  Chrome  96.0.4664.45（正式版本） （64 位）
- Other extensions that might interfere:
i'm sorry,i can't speak English

**Comment by xianren2021** [comment]
谢谢，但是我是点加入黑名单，生成的规则自动是@://www.muzijie.com/*，我很确定。同时，即使我删除@://www.muzijie.com/*一样能搜索到

![2021-12-03_233321](https://user-images.githubusercontent.com/95434795/144629475-5edf5f4a-ac47-4b9e-b2ce-24dba5573ca7.png)

![2021-12-03_233352](https://user-images.githubusercontent.com/95434795/144629489-0b4bae6d-67df-4fce-8206-ccdeec4bd329.png)

**Comment by bcaso** [comment]
![image](https://user-images.githubusercontent.com/32212684/144690240-6648d3ba-83b9-49bf-a70e-c06059ba6c30.png)

用了你的规则，发现一切正常。

![image](https://user-images.githubusercontent.com/32212684/144690257-69e5c52a-5836-4a52-b058-92c9b8dc86e7.png)

**Comment by xianren2021** [comment]
大神，麻烦你看一下是不是我设置有问题，我这还是不行。
![2021-12-04_210929](https://user-images.githubusercontent.com/95434795/144710720-98a1bb1e-04df-476e-8df2-fecbe3f0e474.png)
![2021-12-04_210941](https://user-images.githubusercontent.com/95434795/144710728-a18eca46-6f47-473c-9689-13b9c435f810.png)

![2021-12-04_210952](https://user-images.githubusercontent.com/95434795/144710730-37591bed-4747-4f62-b6f2-3c9d61c1f20d.png)
