### ISSUE TITLE
"Block this site" links don't work on Waterfox Classic

### ISSUE THREAD

**Issue by presola88** [iorate/uBlacklist#153]
## Expected Behavior

Clicking on a "Block this site" link should either show a dialog box, or add the site to the blacklist, depending on uBlacklist's settings.

## Actual Behavior

Clicking on any "Block this site" link doesn't do anything. Other than that, every other function of uBlacklist seems to work fine.

## Steps to Reproduce the Problem

1. Install [Waterfox Classic](https://classic.waterfox.net/).
1. Install uBlacklist.
1. Click on any "Block this site" link.

## Specifications

- OS: Windows 10 x64
- Browser: Waterfox Classic 2021.11 (a 64-bit Firefox 56 based browser)
- Other extensions that might interfere: None, tested with a brand new profile.

**Comment by iorate** [comment]
ref: #41, #75  
Set `dom.webcomponents.enabled` to `true` in about:config.
