### ISSUE TITLE
Add support for leaving notices of blocked results

### ISSUE THREAD

**Issue by as-com** [iorate/ublacklist#158]
It would be useful to have support for leaving a one-line notice that a result was blocked, like in [this userscript](http://www.jeffersonscher.com/gm/google-hit-hider/), instead of completely hiding the result.

Here's what it looks like in the userscript:
![image](https://user-images.githubusercontent.com/3819625/145974894-4e54a569-bc9f-4a53-b50f-9bf957e8a8df.png)

**Comment by iorate** [comment]
I don't have the time or motivation to implement this feature myself.
If you create a pull request, I may merge it.
