### ISSUE TITLE
Add manual to update interval

### ISSUE THREAD

**Issue by fenymufyd** [iorate/uBlacklist#163]
Add manual to update interval in extension subscription options

**Comment by iorate** [comment]
Do you mean that the "Update interval" option is not explained enough on the options page? I think "Update Interval" represents the function of the option well enough, so I have not explained it further. If you want to know the detailed behavior of the option, please read the code.

Or do you mean that https://iorate.github.io/ublacklist/advanced-features#subscription does not explain the option well enough? This site is not actively updated at the moment, although I plan to rewrite it and migrate it to this repository in the future.
