### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by DetachHead** [iorate/ublacklist#167]
how do you add comments in a blacklist? `#` and `//` appear to work but i can't tell for sure

**Comment by iorate** [comment]
Lines that cannot be interpreted as match patterns or regular expressions are simply ignored. `# comment` or `// comment` is never a match pattern or regular expression, so it is always ignored and effectively a comment.

I (the author) use `# comment` in my rules. So you can expect `# comment` to remain a comment even if other types of rules are introduced.

Note: Comments that follow a rule in the same line, such as `*://*.example.com/* # Block example.com and its subdomains`, are not supported.
