### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by DetachHead** [iorate/ublacklist#168]
as mentioned in https://github.com/iorate/ublacklist/issues/167#issuecomment-1000029336:
> Lines that cannot be interpreted as match patterns or regular expressions are simply ignored.

though that could cause lines that are intended to be an actual rule to be silently ignored. i would suggest showing an error on invalid lines (unless they start with `#` or `//` for comments)

**Comment by iorate** [comment]
Good suggestion.

I think a better solution would be to introduce syntax highlighting like https://github.com/uBlockOrigin/uBlock-issues/issues/1134#issuecomment-660490367.
uBlock Origin uses CodeMirror, which seems to work fast enough. CodeMirror looks good to me also in terms of supporting custom key bindings (including vim-style!).
However, I don't have much time right now, and I don't know much about CodeMirror, so it will take some time to introduce it.

I have changed the title of this issue.

**Comment by iorate** [comment]
A CodeMirror-based editor was introduced. It will be relased as v7.0.0.

<img width="634" alt="editor" src="https://user-images.githubusercontent.com/682043/147831642-6461d3fa-c625-45d5-b9ca-690269323c3b.png">
