### ISSUE TITLE
Add Super-preloader Support

### ISSUE THREAD

**Issue by shenez** [iorate/ublacklist#169]
Super-preloader https://github.com/machsix/Super-preloader
A userscript for auto loading paginated web pages. It will join pages together based on the rules.

## Expected Behavior
While Super-preloader is loading more search results pages, ublacklist works on the extra-loaded pages.
## Actual Behavior
While Super-preloader is loading more search results pages, ublacklist only works on the first page (10 result links), not on the extra-loaded pages.

## Specifications

- OS: Win10 
- Browser: Chrome 
- Other extensions that might interfere: 
Super-preloader https://github.com/machsix/Super-preloader

**Comment by iorate** [comment]
dup #136

I'm not going to support all other extensions/userscripts that modify Google search result pages, although pull requests are welcome.
