### ISSUE TITLE
Better Discovery of subscriptions

### ISSUE THREAD

**Issue by Volker-Weissmann** [iorate/ublacklist#170]
Subscriptions work fine, but we need a better way to discover them.
Maybe a wiki?

I found this one: https://github.com/rjaus/awesome-ublacklist

**Comment by iorate** [comment]
I created the subscription page and added links to it to readme and webstore description.
https://iorate.github.io/ublacklist/subscriptions

The initial subscription list was created as follows:
1. Search GitHub with "uBlacklist"
1. Include the 20 "best match" repositories
1. Exclude the repositories without
    - sufficient explanation of what kind of sites the list blocks
    - update within three months
 
Please create pull requests to edit the list.

**Comment by Volker-Weissmann** [comment]
Thank you
