### ISSUE TITLE
https://iorate.github.io/ublacklist/getting-started in extension description is 404ing

### ISSUE THREAD

**Issue by matkoniecz** [iorate/ublacklist#171]
## Expected Behavior

Extension description has no dead links

## Actual Behavior

> You can sync rulesets between your devices by Google Drive or Dropbox, and can also subscribe to public rulesets.

> Usage:
> https://iorate.github.io/ublacklist/getting-started

https://iorate.github.io/ublacklist/getting-started is a dead link

## Steps to Reproduce the Problem

1. Install extension
1. go to about:addons
1. follow https://iorate.github.io/ublacklist/getting-started

## Specifications

- OS: Lubuntu 20.04
- Browser: Firefox 95.0.1
- Other extensions that might interfere: about:addons should not be affected, right?

Seems not reported so far: https://github.com/iorate/ublacklist/issues?q=https%3A%2F%2Fiorate.github.io%2Fublacklist%2Fgetting-started

**Comment by iorate** [comment]
Thank you for reporting this issue.
I have just fixed it.
(It will take a few days for the description on Chrome Web Store to be updated)
