### ISSUE TITLE
Kiwi Browser Support?

### ISSUE THREAD

**Issue by Alex-Mirov** [iorate/ublacklist#172]
Hello

When using the addon on Kiwi for android:

1. The addon tend to crash the browser when i'm trying "other search engines" setting.
2. "block this site" text is not showing at some links in google news section.
3. "block this site" text in google sub images results is missing entirely.

P.S:  "block this site" issues occurs at mobile layout.

Thanks

**Comment by iorate** [comment]
ref #58 #85
Chromium-based browsers for Android are not supported. This extension only happens to work on Kiwi, because it supports Safari on iOS.

(2. and 3. probably occur on iOS as well, and need to be addressed in future)
