### ISSUE TITLE
Support for new search engine

### ISSUE THREAD

**Issue by A3148475824** [iorate/ublacklist#180]
I want ublacklist to support the Russian Yandex search engine.(https://yandex.eu/), it is better to support F search engine (https://fsou.cc/),I don't know if I can support Chinese search engine 360 or God horse.I want to know when the Kiwi browser will be adapted and I want to use Bing.I would love to use the sync feature as wellThank you very much for the efforts of the developers

**Comment by A3148475824** [comment]
I'm an OCD, and I use Firefox, Kiwi, Macaque, Yandex, so I really need the sync feature, otherwise it's too hard for me to use.

**Comment by iorate** [comment]
You may want to create pull requests to support them
