### ISSUE TITLE
Edge crashes when enabling google drive sync

### ISSUE THREAD

**Issue by Frozty4628** [iorate/ublacklist#187]
## Expected Behavior
select google drive sync and click "enable", it should pop up a google auth window. and this works fine on my desktop PC

## Actual Behavior
on my laptop, as long as I select google drive and click "enable" button, browser immediately no response and crashes after a few seconds. re-installing the extension won't help at all. dropbox enable button works fine. 

## Steps to Reproduce the Problem

1, open ext setting
2, click enable sync, select google drive, and click enable button
3, browser crashes after a few seconds.

## Specifications

- OS: Win11 build 22000.376
- Browser: Edge 97.0.1072.55 64bit
- Other extensions that might interfere: tampermonkey (maybe, but scripts & settings in tampermonkey are totally same on both PC and laptop)

**Comment by iorate** [comment]
This problem seems to be a bug of Edge: https://techcommunity.microsoft.com/t5/discussions/edge-stable-crashing-on-extension-function-chrome-identity/m-p/2904069
According to this thread, it will be fixed "in an upcoming update".

**Comment by Frozty4628** [comment]
okay, thanks a lot

**Comment by iorate** [comment]
Please leave a comment here if you still have the problem with Edge 98.

**Comment by rahulmangaldas** [comment]
Still happening in Edge 98, except now it's after the Google login, before I get to the "uBlacklist is asking for permission" page

**Comment by iorate** [comment]
The problem seems to happen even with Edge 99 Canary.
https://techcommunity.microsoft.com/t5/discussions/edge-stable-crashing-on-extension-function-chrome-identity/m-p/2904069/page/2

I will add a workaround for this problem.

**Comment by iorate** [comment]
After v7.4.0 is released, please try this new option:
![useAltFlow](https://user-images.githubusercontent.com/682043/152641326-0cf9b24f-09d6-40fa-98e2-8f002c730ad2.png)
