### ISSUE TITLE
feature_request(rulesets): multiple personal blocklists

### ISSUE THREAD

**Issue by Kristinita** [iorate/ublacklist#190]
### 1. Summary

It would be nice, if would be possible to have multiple personal rulesets (blocklists) for rulesets contributors.

### 2. Example of desired behavior

New option in uBlacklist settings — “Use multiple personal blocklists”.

If the option enabled, blocklists contributor can set multiple personal blocklists. For my case it, for example, “Phishing sites”, “Bookstores”, “Wikipedia automatic translation sites” and “Porn sites”.

uBlacklist user wants to block site. He clicked to “Block this site” → he saw a window “Please, select personal blocklist” → he select blocklist. For example, he adds bookstores to “Bookstores” blocklist, phishing sites to “Phishing sites” list and so on.

#### 3.1. Summary

Save time for people who want to share their personal blocklists with other users (especially if the blocklists are large).

#### 3.2. Details

I’m sure no one wants to see phishing sites in their search results. But I admit that some people want to see bookstores and porn sites in the search results. That is, people would like to use part of my blocklist, but not the full blocklist. I think that the best solution in this case is to divide one big blocklist into rulesets by category, so that users can decide for themselves which category sites they don’t want to see in the search results.

But the separation of the blocklist can take a long time. Currently, uBlacklist ruleset contributors have to do a double job: first they add sites to one big blocklist, then they have to categorize the sites of that big blocklist. For example, [**my personal ruleset**](https://gitlab.com/-/snippets/2237152/raw/main/Google-Hit-Hider-by-Domain-blocklist-2022-1-18.txt) contains 2792 sites (in Google Hit Hider by Domain format) at the time of writing this issue. For most sites, I don’t remember why I added them to the blocklist, what category they belong to. Splitting my blocklist will take me a few days.

If the uBlacklist developers implement the proposed feature, the blocklist contributors will not need to do the extra job of splitting the blocklist.

Thanks.

**Comment by iorate** [comment]
I don't think that this feature is worth implementing with great difficulty (although pull requests are always welcome), because you can extract rules with specific categories using comments even in the current version.
1. Append a category when adding a rule
  - <img width="358" alt="スクリーンショット 2022-01-18 18 45 37" src="https://user-images.githubusercontent.com/682043/149912365-169f4b6e-68fc-49d2-af9c-12247ebda8fd.png">
2. Export the ruleset and filter it
```shell
# Extract rules ending with "# Example"
cat uBlacklist.txt | grep "# Example$" | sed -e "s/ *# Example$//" > uBlacklist-example.txt
```

**Comment by Kristinita** [comment]
**Type: Question** :question:

### 1. Question

@iorate, can you add to the documentation details how the comments syntax works in uBlacklist? It appears to be an [**undocumented feature**](https://iorate.github.io/ublacklist/docs/advanced-features).

### 2. Example

Will uBlacklist work in the case below? Is this the correct syntax?

```text
# This is a long comment explaining why I placed kiraexample.com to the blocklist. See discussion on this issue on https://kiraforum.com/uBlacklist .
*://kiraexample.com/* # Example
```

Thanks.

**Comment by iorate** [comment]
> can you add to the documentation details how the comments syntax works in uBlacklist? It appears to be an undocumented feature.

That's true. Added.

> Will uBlacklist work in the case below? Is this the correct syntax?

Yes. To check the syntax of a rule, you can enter the rule in the options page. Comments and invalid rules are displayed in gray.

![options](https://user-images.githubusercontent.com/682043/149944319-4b99da5b-b109-44ce-806b-c09d3717b4ff.png)

**Comment by BrandonKMLee** [comment]
@iorate some ideas: The ability to import uBlock blocklist into uBlacklist. This is merely downloading the lists online, and then does string concatenation.
