### ISSUE TITLE
Breaks page thumbnails

### ISSUE THREAD

**Issue by Artim96** [iorate/uBlacklist#2]
The extension works great, especially since Personal Blocklist stopped working entirely, but it also seems to break extensions that insert page thumbnails, like SearchPreview, which Personal Blocklist didn't.
Could you somehow improve coexistence?

**Comment by iorate** [comment]
Thank you for reporting an issue. I have uploaded a new version that improves compatibility with SearchPreview (except that thumbnails are not inserted to blocked pages). Please try it.
