### ISSUE TITLE
Broken after Google's latest update?

### ISSUE THREAD

**Issue by danlugo92** [iorate/ublacklist#212]
## Expected Behavior

Show "block this site" links alongside each result.

## Actual Behavior

No "block this site" links alongside each result.

## Steps to Reproduce the Problem

1. Do a Google search if you got Google's latest update.

## Specifications

- OS: Mac OS Monterrey (Latest Version)
- Browser: Firefox (Latest Version)
- Other extensions that might interfere: uBlock Origin

![Screen Shot 2022-02-21 at 13 08 52](https://user-images.githubusercontent.com/32064271/155007555-e30d86c6-c5f2-4f50-8b31-fbe42d8993b3.png)

**Comment by iorate** [comment]
Have you changed the user agent from the default?

**Comment by chris-vecchio** [comment]
I was having the same issue. Toggling the 'Hide the "Block this site" links' option on and off again brought them back.

![ublacklist](https://user-images.githubusercontent.com/19472296/156757999-90506704-c2cf-4411-92cd-99c35882bb55.png)
