### ISSUE TITLE
Support for YouTube

### ISSUE THREAD

**Issue by uetchy** [iorate/ublacklist#218]
It would be cool if uBlacklist could block specific channels on YouTube.

Well, I've already implemented it on my fork and have been using it daily, and I thought it was so convenient that it should be shipped with uBlacklist as well.
I'll open a PR if you are kind of ok about such an addition since it will add API to the core to support exact matching URLs; still backward-compatible, though.

**Comment by echelonxray** [comment]
I think this would be a great.  The YT search is already terrible, promoting and spamming the same cookie-cutter channels to the top of searches.  I can not longer find good content and many of these "creators" annoy me.  I'd love to just blacklist them from results.

**Comment by uetchy** [comment]
@iorate Any thoughts?

**Comment by jmonastery** [comment]
[De-Mainstream Youtube](https://github.com/miscavage/De-Mainstream-YouTube-Extension) is probably better suited to this task.

**Comment by iorate** [comment]
@uetchy 
Sorry for the delay in responding.
To be honest, I think that support for YouTube search is outside the scope of this project (currently only web search engines are supported), and there may be more appropriate extensions for YouTube filtering (perhaps the extension introduced by @jmonastery  would be useful).
However, if you create a pull request to support YouTube and maintain it, I am open to that.

**Comment by uetchy** [comment]
I don't think De-Mainstream YouTube support what I described at all🤷‍♀️, and still personally think this falls into the project scope if we broaden the project goal to `block specific source from search results`👍

Anyways, I'm fine forking the project and maintaining it myself. I won't push something you don't want to maintain.

**Comment by iorate** [comment]
@uetchy OK, please open a pull request.

**Comment by egrieco** [comment]
@uetchy I was about to open an issue for this. Looking forward to your pull request.

[SkyTube](https://github.com/SkyTubeTeam/SkyTube) (Android app) has this and it makes YouTube far more tolerable.

**Comment by tosstosstoss** [comment]
> 

You can use extension channel-blocker for chrome
