### ISSUE TITLE
Support for www.kagi.com

### ISSUE THREAD

**Issue by fady0** [iorate/ublacklist#223]
Please consider add support if possible.

## Specifications

- OS: Macos
- Browser: firefox

**Comment by Chamiu** [comment]
I think so.

----
Specifications

OS: macOS Monterey
Browser: Safari

**Comment by karolzlot** [comment]
Please reopen

**Comment by Chamiu** [comment]
Kagi search is paid service.
Therefore, more vote [Add uBlacklist support - Kagi Feedback](https://kagifeedback.org/d/262-add-ublacklist-support).

**Comment by rsuwa** [comment]
Vlad, who runs Kagi, says:

> We can not expand our backend now to support something like 100,000 long blacklist. The cost of processing this per for every query would be non-trivial as well as there would be a latency penalty.
> I understand uBlackist extension is open-source - would you be open to submitting a patch to support Kagi's front-end?
https://kagifeedback.org/d/262-add-ublacklist-support/19

As a Kagi user myself, I would love to be able to use uBlacklist with Kagi and will try to implement it.

**Comment by lsomm** [comment]
@rsuwa Do you want help with that?

**Comment by cleverdevil** [comment]
Chiming in to say I’d also love support for Kagi. Following with interest!

**Comment by Chamiu** [comment]
[Kagi Search](https://kagi.com/) come uBlacklist ♪

[Add kagi.ts search-engine by GeorgeIsInTheAir · Pull Request #483 · iorate/ublacklist](https://github.com/iorate/ublacklist/pull/483)
And
[Kagi Search Changelog](https://kagi.com/changelog#4264)
