### ISSUE TITLE
Add-on suddenly stopped working.

### ISSUE THREAD

**Issue by KirkH420** [iorate/ublacklist#229]
## Actual Behavior
I just noticed that it suddenly quit working. The 'Block this site' link was gone and it wasn't showing the 'show blocked' link either. It seemed to still be working on BING, but not DDG. Then I look here and see that DDG code was a target of the recent update as of 5-5 (today). Uninstall/Re-install seems to have revived it.

## Steps to Reproduce the Problem

1. Just run a search on DDG << I don't see it here
1. Then run a search on Bing << I see it there.
1. I tested several times, blocking was no longer working either.

## Specifications

- OS: LTSC 21H2
- Browser: Firefox 96
- Other extensions that might interfere: doubt it. I haven't changed anything
- The only change that I see is that the add-on updated. I uninstalled add-on and re-installed it from the Firefox add-on site and it started working again. Might be something to be aware of.... just thought I'd let you know.

**Comment by iorate** [comment]
Thank you for your report.
Just today's update addressed the DDG issue.
I guess you installed the updated version when you "reinstalled from the Firefox add-on site".
