### ISSUE TITLE
Suggestion: Show the number of blocked sites on the icon

### ISSUE THREAD

**Issue by timonwong** [iorate/uBlacklist#23]
Similar to uBlock, Is there any opportunity to provide a feature like this?

![image](https://user-images.githubusercontent.com/1398228/70883977-8cf9c980-200f-11ea-8d35-4c4c0467f72b.png)
 
And thanks for your awesome work :)

**Comment by iorate** [comment]
Thank you for your feature request, but I will not implement the feature. I think it is redundant because the number of blocked sites are already shown inside search result pages. Pull requests are welcome though.

**Comment by iorate** [comment]
Oh, the number of blocked sites is not shown now. It will be fixed in v3.3.2.
