### ISSUE TITLE
Support for Brave Search

### ISSUE THREAD

**Issue by MagiDruid** [iorate/ublacklist#233]
Thank you for developing this wonderful extension. 

Please consider adding support for Brave's new search engine: search.brave.com

Kind Regards.

**Comment by rsuwa** [comment]
@MagiDruid I'm developing it right now!

**Comment by MagiDruid** [comment]
Thank you! Much appreciated. Will rate the extension highly, recommend to others and support future development. All the best.

**Comment by iorate** [comment]
#244 is merged
