### ISSUE TITLE
Support for Yandex Search

### ISSUE THREAD

**Issue by MagiDruid** [iorate/ublacklist#234]
Please consider adding support for Yandex Search:

USA =  yandex.com
Russia = yandex.ru
Belarus = yandex.by 
Kazakhstan = yandex.kz
Uzbekistan = yandex.uz
Turkey = yandex.com.tr

Thank you. Kind Regards.

**Comment by ibrahimBeladi** [comment]
There is [this PR](https://github.com/iorate/ublacklist/pull/217), but it looks stale

**Comment by MagiDruid** [comment]
Thanks for drawing my attention to this. Will look more carefully next time.

**Comment by iorate** [comment]
Watch #217
