### ISSUE TITLE
Add Yahoo! JAPAN support

### ISSUE THREAD

**Issue by munierujp** [iorate/ublacklist#235]
Retry for #90

For Japanese users, [Yahoo! JAPAN](https://search.yahoo.co.jp/) is the second most popular search service and its share is 16.2%.[^1]

[^1]: https://gs.statcounter.com/search-engine-market-share/all/japan/

**Comment by munierujp** [comment]
I'm now developing it.

<img width="1152" alt="スクリーンショット 2022-05-20 0 10 45" src="https://user-images.githubusercontent.com/20086673/169330949-50eefc9a-72dd-4934-abaf-9ef4ead06391.png">

**Comment by iorate** [comment]
@munierujp Thank you for your contribution.
Could you please update the website later?

**Comment by munierujp** [comment]
@iorate You're welcome. I'm glad to contribute to this project. 

>Could you please update the website later?

Are you referring to [this page](https://iorate.github.io/ublacklist/docs/advanced-features)?

**Comment by iorate** [comment]
Yes, and [here](https://iorate.github.io/ublacklist/docs#features).

**Comment by munierujp** [comment]
@iorate I did it! #237
