### ISSUE TITLE
'Featured snippets' still show 

### ISSUE THREAD

**Issue by EmSixTeen** [iorate/uBlacklist#24]
Hi there. The extension is great, useful for clearing results of the repeat bad offenders. Unfortunately, 'Featured snippets' still show up even when from blocked sites. If possible, could these also be blocked? And/or an option given to do so?

![image](https://user-images.githubusercontent.com/149746/72783419-a7cee780-3c26-11ea-8c97-74dd90990d37.png)

**Comment by iorate** [comment]
Would you try the latest version (v3.3.0) published a few hours ago?
<img width="683" alt="Screen Shot 2020-01-21 at 18 29 30" src="https://user-images.githubusercontent.com/682043/72792231-03779000-3c7c-11ea-9b56-b635d364f4f6.png">

**Comment by EmSixTeen** [comment]
The extension seems to have updated automatically to 3.3.0, and the Featured Snippet is now gone - working great, thanks!

Also, apologies for not including the version number in my first post.
