### ISSUE TITLE
subscriptions are not syncing

### ISSUE THREAD

**Issue by avincent98144** [iorate/ublacklist#241]
## Expected Behavior

Full sync across MacOS, iPadOS and iOS

## Actual Behavior

Subscribes were initiated native in MacOS, appear in the syntax list, but that same list does not appear on iOS/iPadOS devices, nor do the actual subscription appear under the SUBSCRIPTIONS section of the prefs on the iOS/iPad devices. dropbox sync appears to be working as expecting.

## Steps to Reproduce the Problem

1.
1.
1.check iOS/iPadOS devices extension prefs, pull a manual sync

## Specifications

- OS: MacSO 12.4, iOS 15.5 and iPadOS 15.5
- Browser: STP 146
- Other extensions that might interfere: none that jump out at me.

**Comment by HoneyLuka** [comment]
Yes, because iOS/macOS sync feature not implemented by iCloud. You should use Google Drive or Dropbox to sync

**Comment by avincent98144** [comment]
I was not expecting iCloud sync, but forgot to specify that I al already using  dropbox and the devices that the subscriptions are not syncing to have the same access API token.

**Comment by avincent98144** [comment]
oh .. see that that I *DID* already mention dropbox..........
