### ISSUE TITLE
Clicking "Block this site" on Bing search pages attempts to block Bing.com instead of the correct domain

### ISSUE THREAD

**Issue by rubberbander** [iorate/ublacklist#242]
## Expected Behavior

Clicking the "Block this site" links next to page urls on Bing search pages should bring up the "Block this site" dialog with a pattern for the domain of the site in the search results.

## Actual Behavior

Clicking the "Block this site" link brings up the "Block this site" dialog, but with a pattern for bing.com instead of the domain for the webpage. I believe that this is because Bing uses referral links for it's outgoing links. 

## Steps to Reproduce the Problem

1. Go to Bing.com with the uBlacklist extension installed.
2. Do a search for anything.
3. Click the "Block this site" link next to a url
4. The pattern to be added will be for bing.com regardless of what the website actually is.

## Specifications

- OS: Fedora Linux 36 Workstation
- Browser: Mozilla Firefox 101.0
- Other extensions that might interfere: n/a

**Comment by iorate** [comment]
This problem seems inevitable because URLs returned by Bing are of form `https://www.bing.com/ck/...` and do not include real URLs when *''Open links in new tab"* is turned on.

Please turn off *"Open links in new tab"* when you use this extension with Firefox and Bing.
