### ISSUE TITLE
'Options' button can not working anymore on Safari

### ISSUE THREAD

**Issue by HoneyLuka** [iorate/ublacklist#246]
It is working in version 7.6.0, after that it is broken.

## Expected Behavior
Click 'Options' button on popup, it should open extension options page.

## Actual Behavior
Click 'Options' button on popup, nothing happened.

## Steps to Reproduce the Problem

1. Search anything on google.
2. Click 'Block this site' on web content, or click uBlacklist icon on Safari toolbar
3. Click 'Options' button

## Specifications

- OS: iOS 15.5 / macOS 12.4

**Comment by iorate** [comment]
@HoneyLuka Thank you for your report.
I cannot debug the Safari version right now.
Could you please tell me what error messages the background page shows?

**Comment by HoneyLuka** [comment]
No messages appear in console. That's weird.
It seems like ```sendMessage('open-options-page')``` doesn't get called.

I try to call ```browser.runtime.openOptionsPage()``` in background page console, it's working properly.

**Comment by iorate** [comment]
Thanks!
