### ISSUE TITLE
[enhancement]: static position of "Block this site button"

### ISSUE THREAD

**Issue by luntik2012** [iorate/ublacklist#256]
"Block this site" button has different positions depending on search result url len, so It's hard to block multiple urls just clicking lmb. It's needed to look at the result and move the mouse every time.
So is it possible to add some indent before this button or something like that?

**Comment by munierujp** [comment]
How about displaying it at the bottom of the search results element?

<img width="858" alt="スクリーンショット 2022-07-26 19 25 44" src="https://user-images.githubusercontent.com/20086673/180985074-d09f1d97-07c8-4dcc-abdf-cd1f596caf5f.png">

**Comment by iorate** [comment]
It doesn't look very good to me.

In the future, if I ever update this extension to display the block button in a different position than it is now, I would like to implement it like [HoHSER](https://github.com/pistom/hohser). It looks cool to me.
