### ISSUE TITLE
[UI Enhancement] : Extend rule/text editing space horizontally

### ISSUE THREAD

**Issue by MagiDruid** [iorate/ublacklist#260]
Hello.

Currently, the height of the rule/text editing space within uBlacklist can be adjusted vertically, but not horizontally. Please consider implementing the latter (see screenshot).

Thank you for your time and consideration. Kind Regards. 

![Screenshot](https://user-images.githubusercontent.com/100071592/183724356-fb7bafaf-ada3-4f89-9880-34752442574a.jpg)

**Comment by iorate** [comment]
Declined.
I don't think it is useful at all.
