### ISSUE TITLE
Search Blocking not working on shopping tab

### ISSUE THREAD

**Issue by Tegal1453** [iorate/ublacklist#261]
## Expected Behavior
I blocked aliexpress.com. shopping tab results should block the site.
## Actual Behavior
I blocked aliexpress.com. When I search in "All" result I don't see aliexpress any more, however, in shopping tab they are still there
## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- OS: MacOS Monterey 12.5
- Browser: Google Chrome
- Other extensions that might interfere:

**Comment by e-t-l** [comment]
@iorate petition to reopen this. Is it possible to make the extension work with the the Shopping tab for Google (or DDG)? Would be a great feature if so
