### ISSUE TITLE
AutoPager in Greasy Fork conflicts with uBlacklist highlight function

### ISSUE THREAD

**Issue by alexoftheweek** [iorate/ublacklist#266]
**Extensions that might interfere: Autopager(https://greasyfork.org/zh-CN/scripts/419215-自动无缝翻页)**

When AutoPager is on, only the first page of the search results site will be highlighted. Sites after page one are unable to achieve the highlight function.

eg. who.int has been highlighted in the rules as green, but because this search result appears on the fourth page, highlighting disappears. (Pic 1)

After closing AutoPager, the highlight function comes back to its normal state. (Pic 2)
<img width="740" alt="Capture d’écran 2022-08-27 à 12 03 57 PM" src="https://user-images.githubusercontent.com/91208638/187017863-3d0b612f-110f-4fee-9253-8e63650b6873.png">
<img width="702" alt="Capture d’écran 2022-08-27 à 12 04 41 PM" src="https://user-images.githubusercontent.com/91208638/187017866-a52bd7f4-c167-427c-8678-427fa5273593.png">

**Comment by iorate** [comment]
ref #59 #65 #86 #134 #136

I'm not going to support all other extensions/userscripts that modify Google search result pages.
I recommend AutoPagerize-based extensions such as [uAutoPagerize](https://chrome.google.com/webstore/detail/uautopagerize/kdplapeciagkkjoignnkfpbfkebcfbpb).
