### ISSUE TITLE
Not working on Qwant.com but works on Qwant lite

### ISSUE THREAD

**Issue by gggirlgeek** [iorate/ublacklist#268]
## Expected Behavior
See Block This Site buttons on Qwant.com and Lite.Qwant.com Searches
## Actual Behavior
No buttons showing on Qwant.com but they show on lite.qwant.com
## Steps to Reproduce the Problem

1. Install ublocklist addon in Firefox or Chrome
2.Enable Qwant in the options of the addon
3.Do a search on Qwant.com= no buttons to block the search hit show.
4.Do a search in lite.qwant.com = buttons showing
5.Buttons showing in Google, DDG, and Yandex

## Specifications

- OS: Windows 10
- Browser: Firefox v. 104.01 and Slimjet v. 36.0.2.0 (based on Chromium 104.0.5112.39)
- Other extensions that might interfere: Lastpass is the only other extension installed in Firefox
- Tried in new Firefox profile
- This issue was resolved previously I think??? https://github.com/iorate/ublacklist/pull/179

**Comment by MightyPork** [comment]
I'm running version 8.2.4 in Vivaldi and this bug still happens - exactly as described. Am I doing something wrong?

Qwant is enabled in the "other search engines" list.

Example URL:

https://www.qwant.com/?client=brz-vivaldi&q=set-cookie+url+encoding&t=web
