### ISSUE TITLE
blacklist augmented with over 100 new domains, mostly from .ee top domain and a few others

### ISSUE THREAD

**Issue by levitation** [iorate/ublacklist#273]
Hello, I forked the list created by [franga2000](https://github.com/franga2000) and added mostly various .ee (Estonian) domains which redirect to Aliexpress. There are also a few domains with other top-level domains than .ee added. So far I have added over 100 domains in total. You might want to refer to this blacklist in your list of lists.
It is here: https://github.com/levitation-opensource/aliexpress-fake-sites

**Comment by newage11** [comment]
good jobs

**Comment by iorate** [comment]
@levitation You might want to open a pull request to add your list to the "Copycat sites" section.
