### ISSUE TITLE
Ublacklist seems to be incompatible with automatic pages ...

### ISSUE THREAD

**Issue by sakuraes** [iorate/ublacklist#278]
The plug -in successfully blocked the spam website, but the search results on this page decreased. I tried to use the automatic page plug -in, but found that Ublacklist does not seem to block the new page. What I said is a bit abstract.
It successfully shielded the garbage site from the search result on the first page, so that there were only two search results on the first page, so the plug -in of my automatic page turned the plug -in for the next page, but！Ublacklist does not seem to block the next page of garbage sites.

**Comment by iorate** [comment]
See #266 etc.

I'm not going to support all other extensions/userscripts that modify Google search result pages.
I recommend AutoPagerize-based extensions such as [uAutoPagerize](https://chrome.google.com/webstore/detail/uautopagerize/kdplapeciagkkjoignnkfpbfkebcfbpb).
