### ISSUE TITLE
Blocklist rules added in different ways overwrite each other

### ISSUE THREAD

**Issue by danny0838** [iorate/ublacklist#282]
## Steps to Reproduce the Problem
1. Open a tab X with Google search for something.
2. Open the options page and add some rules, such as `*://*.example.com/*`.
3. Go to tab X and block a site with the `Block this site` button.
4. Open the options page, and the rules added in step 2 ARE MISSING.

**Comment by iorate** [comment]
It's by design; it's hard work to fully synchronize settings across multiple tabs, so some compromises must be made.
