### ISSUE TITLE
uBlacklist not working?

### ISSUE THREAD

**Issue by PanchamBro** [iorate/ublacklist#287]
For some reason, the blacklist feature of uBlacklist is failing to remove the site in question.

I noticed it under Google while private browsing on Firefox, where Softtonic was showing up on Google search results, even though I had blocked the site.
![image](https://user-images.githubusercontent.com/5955312/198411561-e8828765-6205-4507-91c9-c9ba1f329875.png)
![image](https://user-images.githubusercontent.com/5955312/198411579-96d7eeed-8f11-47ac-9198-34e2661e2e4d.png)

I then tried DuckDuckGo, this time without private browsing, and the extension still didn't work.
![image](https://user-images.githubusercontent.com/5955312/198411698-fd8d4a22-b246-4663-be39-b13a6d3bec22.png)
![image](https://user-images.githubusercontent.com/5955312/198411812-37b718ae-8255-46bb-9d48-424a1362c81c.png)

I'm really not sure if the extension is currently flawed or not, but it's not blocking the sites that I want it to block.

**Comment by PanchamBro** [comment]
Update: reinstalling the extension and restarting Firefox did not work.

**Comment by jjoyc3** [comment]
Same issue for me on Firefox with DuckDuckgo. All my blocked sites are no longer blocked and show up in results. Additionally I have set the extensions to hide 'the number of blocked sites and the "Show" link' - but now this is no longer hidden

**Comment by iorate** [comment]
v8.1.0 is broken due to a breaking change of goober@2.1.11.

**Comment by iorate** [comment]
v8.1.1 was published in Firefox Add-on.

The Chrome version is under review.

**Comment by vphantom** [comment]
Thank you for looking into this. Today I realize how much I wouldn't want to search the web without uBlacklist. 😉

**Comment by PanchamBro** [comment]
Thanks for addressing the issue! I wouldn't want to have to scorn at seeing Softonic or any other website I had blocked appear on search results.

**Comment by TonyQuu** [comment]
Just to add, currently not working for Bing

**Comment by bcaso** [comment]
uBlacklist Version: 8.1.1
Chrome: Version 106.0.5249.91 (Official Build) (64-bit), Installed by scoop.
open search in new tab，I tested google, duckduckgo, bing, but no one worked.


But if I open a new window to search, it will work.

I prefer to search for content like this now.

`s.bat`

```bat
REM open chrome in new window
call "cmd /c start chrome --args --new-window https://google.com/search?q="%*" https://duckduckgo.com/?q="%*" https://bing.com/search?q="%*" https://www.baidu.com/s?wd="%*" "

ping -n 10 127.0.0.1 1>nul 2>nul
```

example: search 'a b c' on google, duckduckgo, bing, baidu:

![image](https://user-images.githubusercontent.com/32212684/202088291-bbe3c01e-4738-4e0c-af38-9168e210299e.png)

https://github.com/bcaso/Computer-Science-Whitelist/blob/main/search_content_by_multi_search_engine.ipynb

**Comment by bitdeep** [comment]
Had to mark "Hide the number of blocked sites and the "Show" link" to avoid the page flick that is annoying, if you guys avoid page flick or put it in another place, can be interesting to keep it.
