### ISSUE TITLE
iCloud sync support feature request

### ISSUE THREAD

**Issue by kris-anderson** [iorate/ublacklist#291]
Current cloud syncing allows for both Google Drive and Dropbox.

I would love for the ability to use iCloud for cloud syncing so I can keep my iPhone, iPad, and macOS devices in sync.

**Comment by HoneyLuka** [comment]
Sorry, there is no plan to support iCloud sync, please use Google Drive or Dropbox to sync. 
It seems to be difficult to exchange data between iOS App and Extensions.

Is there a known Extension that can be synced via iCloud? I'd love to look into how it does it!

**Comment by kris-anderson** [comment]
All good, just thought I would ask since I didn't see this brought up in the past. 

I install as few apps as possible, none of them from Google, and Dropbox has caused CPU related issues for me in the past on macOS so I avoid that as well. But at least those are options that will likely meet the needs for most people for this great app!

An extension I use that supports iCloud syncing is xSearch:
https://apps.apple.com/us/app/xsearch-for-safari/id1579902068

It isn't open source though, so I don't think that helps you in this case.

![image](https://user-images.githubusercontent.com/1562427/201515192-714a7a3d-4ce4-43b6-8d18-21e5fe23049c.png)

**Comment by HoneyLuka** [comment]
Thank you, I will try it later. But I can't guarantee that this feature will be added.

I think that even iCloud sync is supported, the user needs to open the app manually to sync (App part), but if use the current sync function, you don't need the app, it is automatically synced by Extension (Extension part).

By the way, Google Drive and Dropbox sync using the web API, so you don't need to install any additional apps, you just need an account.
