### ISSUE TITLE
ublacklist can't work when i sign in with google account

### ISSUE THREAD

**Issue by kasie-zhang** [iorate/ublacklist#293]
## Expected Behavior
Button `Block this site` appears in the side of each url.

## Actual Behavior
I have turned off other plugins.
When i signed in and using normal mode, the Button `Block this site` disappeared, it seems that the plugin doen't work.
When i signed out or using incognito mode, it works well.

## Specifications

- OS: Win
- Browser: Chrome 107.0.5304.107
- Plugin Version:  8.1.1

**Comment by fan123199** [comment]
I have the same problem. same Specifications

OS: Win
Browser: Chrome 107.0.5304.107
Plugin Version: 8.1.1

**Comment by raShMan777** [comment]
same here.

OS: Win
Browser: Firefox 107.0 Build ID: 20221110173214
Plugin Version: 8.1.1

**Comment by iorate** [comment]
Thank you for your report.
I think this is the same problem as #290. Google is probably testing the new layout on a limited number of accounts.
Please subscribe to #290.
