### ISSUE TITLE
uBlacklist FireFox not working on Google results (Google news still OK, DDG still OK)

### ISSUE THREAD

**Issue by obamaphone** [iorate/ublacklist#295]
![Screen Shot 2022-11-25 at 12 38 07 PM](https://user-images.githubusercontent.com/20824557/204040481-0535439b-bed6-4676-b733-b148c972f56e.png)
![Screen Shot 2022-11-25 at 12 38 00 PM](https://user-images.githubusercontent.com/20824557/204040483-d0cea65a-260f-4806-8ace-6f807a1c1229.png)
![Screen Shot 2022-11-25 at 12 37 52 PM](https://user-images.githubusercontent.com/20824557/204040484-2f669701-b9ee-46f2-bad8-441a6a939076.png)
![Screen Shot 2022-11-25 at 12 39 54 PM](https://user-images.githubusercontent.com/20824557/204040725-22504395-59df-428b-a4a8-7073e90ffa24.png)

**Comment by iorate** [comment]
Thank you for your report.
I think this is the same problem as https://github.com/iorate/ublacklist/issues/290. The fact that news results are not affected is important information.
Please subscribe to https://github.com/iorate/ublacklist/issues/290.
