### ISSUE TITLE
Suggestion - Missing validation to prevent duplicate entries

### ISSUE THREAD

**Issue by YouJerName** [iorate/ublacklist#297]
I found that there were duplicate entries of the same input (same site with same pattern/regex syntax, e.g. 2 entries of "/www.foobar\.com"). 

I used Microsoft Excel's "Remove Duplicates" function to trim the duplicate. 

Is this normal behavior? Maybe certain validation can be put in place to prompt a reminder to user that it was already in the list before and only unique input should be appended?

**Comment by iorate** [comment]
Unless you edit rules manually, duplicate rules should not be generated because you cannot block again a search result that has already been blocked.

If you edit rules manually, duplicates are not and will not be checked.
