### ISSUE TITLE
Don't work with Google continuous scrolling

### ISSUE THREAD

**Issue by haukeng** [iorate/ublacklist#299]
## Expected Behavior
blocked sites will not be display
## Actual Behavior
Block don't work after results loading with continuous scrolling
<img width="742" alt="google-search-result" src="https://user-images.githubusercontent.com/93363611/206953010-97f5eed9-116e-4863-afd0-d50622128034.png">
## Steps to Reproduce the Problem

1. Logged in 
1. Search something

references: [Google switching to continuous scrolling for desktop Search results](https://9to5google.com/2022/12/05/google-search-continuous-scrolling-2/)

## Specifications

- OS: Windows 11 22H2
- Browser: Firefox 107.0.1(64-bit)
- Other extensions that might interfere: None

**Comment by TBat** [comment]
I've been getting this exact problem on Windows 10 Chrome.

Only the first dozen or so search results display the "Block this site" button, and within these results the desired sites are blocked normally. But below that point, blocked sites start appearing again and NONE of the search results have the "Block this site" button.
