### ISSUE TITLE
DuckDuckGo compatibility 

### ISSUE THREAD

**Issue by Jaruso** [iorate/uBlacklist#3]
This extension should be expanded to work with DuckDuckGo as well.

**Comment by iorate** [comment]
I don't use DuckDuckgo, so honestly I have no motivation to add DuckDuckGo support and maintain it.
Thank you for your comment.

**Comment by vphantom** [comment]
If you closed the issue instead of tagging it as "won't implement, but contributions welcome", does this mean you wouldn't be interested in a pull request?

I haven't worked in TypeScript before, but I might be tempted to give it a try based on the example you set with StartPage.

**Comment by Semro** [comment]
I've tried to [add duckduckgo](https://github.com/Semro/uBlacklist/commit/ae5b4189a3aa44bed43b720ca3c600a93ec0d746), but solution doesn't work and I can't figure out why.

**Comment by vphantom** [comment]
The `matches` regex seems to be too restrictive. My DuckDuckGo URLs are usually just `https://duckduckgo.com/` (no `search?`). Maybe that's it?

**Comment by iorate** [comment]
Re-opened. I'm not so willing to add support for other engines by myself, but pull requests are welcome.

DuckDuckGo seems to accept both HTTP and HTTPS, and both GET and POST.
![settings](https://user-images.githubusercontent.com/682043/73039980-4ebbb980-3e9b-11ea-8e98-ca6ad3512c90.png)

So `matches` should match more URLs, for example (not tested),
```typescript
matches: [
  '*://duckduckgo.com/?*',  // GET
  '*://duckduckgo.com//',   // POST
],
```

**Comment by iorate** [comment]
Added initial support for DuckDuckGo (v3.5.0).

**Comment by vphantom** [comment]
Out of curiosity, are you sure it's v3.5.0? I don't see "duckduckgo" in the manifest file.

**Comment by iorate** [comment]
Yes it's v3.5.0. Support for other search engines is dynamically injected, and so doesn't appear in the manifest file.

**Comment by vphantom** [comment]
Ah ha!  I had to re-enable StartPage and also enable DDG in uBlacklist's options after the update. I see now. :) Blocking seems to work well. No injection of "add" links in my layout, but I can live with that tradeoff.

Thank you very much for your efforts!

**Comment by iorate** [comment]
@vphantom Aren't the "block this site" links shown on DDG with the "Hide the 'block this site' links" option off? If not, would you please open an issue and tell me your environment (OS, browser, DDG settings, and other extensions working on DDG)?

Known restrictions for DDG:
- Does not work for search types other than 'All' ('Images', 'News' and 'Videos').
- Does not work on Firefox if the HTTP method is set to 'POST'. (I just found this and will fix it later)
