### ISSUE TITLE
Where to insert URL exactly 

### ISSUE THREAD

**Issue by Souka-gif** [iorate/uBlacklist#30]
Hello, 

Im new and I don't know how to use blacklist. I REALLY need to hide a url or remove it from google search. The url contains videos and I hope you could let me know how I can message you to guide me, if possible. 

Best regards and thank you for creating such an extension.

**Comment by iorate** [comment]
Sorry, I don't understand what you say very well.

If you want to block URLs containing "videos", add a rule `/videos/` in the options page.
<img width="630" alt="options_videos" src="https://user-images.githubusercontent.com/682043/77243134-d4fd3d80-6c49-11ea-908b-88a5a4fe363d.png">
