### ISSUE TITLE
Subscriptions ignore the "Update Interval" setting and update on every startup

### ISSUE THREAD

**Issue by lyaaz** [iorate/ublacklist#307]
## Expected Behavior
Subscriptions don't update on firefox startup unless update time exceeded
## Actual Behavior
Subscriptions update on every startup
## Steps to Reproduce the Problem

1. Close firefox
1. Start firefox
1. Repeat 1 and 2, subscriptions update every time.

## Specifications

- Browser: Firefox 108.0.1

**Comment by iorate** [comment]
It's intended behavior.
