### ISSUE TITLE
Is there a better way to block websites' polluted search results?

### ISSUE THREAD

**Issue by pixiandouban** [iorate/ublacklist#309]
Many websites search results have been pulluted by SEO e.t.c. （for example AAA.com/q=BBB, BBB is polluted keywords,）  I remember there's a way to block "q=*", however now it seems not work.

**Comment by pixiandouban** [comment]
It seems that Regular expressions should be used. For example, if `/vendors\?q=/` is added in the blocking rules, [url1](https://www.hvid.be/collections/vendors?q=%E4%B9%B0%E7%90%83%E5%93%AA%E4%B8%AA%E7%BD%91%E7%AB%99%E5%A5%BD-(%E2%8F%A9%E6%8E%A8%E8%8D%90%E3%8A%99%EF%B8%8Fy759.com%20%E2%8F%AA)-%E4%B8%96%E7%95%8C%E6%9D%AF%E4%B9%B0%E7%90%83%E5%9C%A8%E5%93%AA%E4%B8%AA%E7%BD%91%E7%AB%99-%E4%B8%96%E7%95%8C%E6%9D%AF%E5%AE%98%E6%96%B9%E4%B9%B0%E7%90%83%E5%B9%B3%E5%8F%B0-(%E2%8F%A9%E6%8E%A8%E8%8D%90%E3%8A%99%EF%B8%8Fy759.com%20%E2%8F%AA)-%E7%B1%B3%E4%B9%90%E4%BD%93%E8%82%B2%E6%B3%A8%E5%86%8C-%E6%83%B3%E4%B9%B0%E8%B6%B3%E7%90%83%E5%BD%A9%E7%A5%A8%E5%9C%A8%E5%93%AA%E9%87%8C%E4%B9%B0) can be blacked.

**Comment by iorate** [comment]
Already resolved
`*://*/*?q=*` will also work
