### ISSUE TITLE
All results get blocked

### ISSUE THREAD

**Issue by cyatarow** [iorate/ublacklist#312]
## Expected Behavior
When I tap on "Block this site", the correct domain is shown and gets blocked.

## Actual Behavior
"www.google.com" is selected as the target domain, and ALL RESULTS get blocked.
However, in desktop mode, this bug doesn't occur.

## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Browser: Firefox for Android (Beta)
- Other extensions/add-ons: don't matter. This bug occurs even when other add-ons are disabled (I tested it in Private Browsing).

- Search engine: Google
- Language: (doesn't matter)
- Region: (doesn't matter)

**Comment by iorate** [comment]
Thank you for your report.
