### ISSUE TITLE
Consider mirroring repo to Codeberg

### ISSUE THREAD

**Issue by throwaway-d** [iorate/ublacklist#314]
Please consider mirroring repos to Codeberg because:

1. Codeberg is libre, free, open-source, privacy-friendly, non-profit, really fast
2. GitHub has bloated interface with captcha & GitHub is privacy-invasive, Microsoft-owned, proprietary, vendor-lock-in, Tor-hostile
3. GitHub Copilot attacks copyleft licensing
4. People on Codeberg like me can contribute to the project
5. GitHub can take down our repos

Here are some sources for you written by me: https://codeberg.org/Recommendations/Mirror_to_Codeberg

**Comment by iorate** [comment]
Not planned.

**Comment by throwaway-d** [comment]
@iorate Can you mind please explain more about the reasons that you decided not to mirror?
