### ISSUE TITLE
'Block this Site' are not shown at proper positions on "People Also Ask" lists 

### ISSUE THREAD

**Issue by matthewbeke** [iorate/ublacklist#316]
It would be great if you could disable the 'block this site' button within the "people also ask" section so it does not make it twice as large 

![image](https://user-images.githubusercontent.com/80664169/218275168-20383248-20f3-46b1-a518-a6e55f398027.png)

- Search engine: Google
- Language: American English
- Region: USA

**Comment by iorate** [comment]
Not confirmed yet

**Comment by iorate** [comment]
confirmed
