### ISSUE TITLE
Not working on (new) Bing.com

### ISSUE THREAD

**Issue by maxcurzi** [iorate/ublacklist#318]
## Expected Behavior
In Bing, "Block this site" link appears somewhere near each search result to block those domains.
On other search engines (Google, DuckDuckGo) the extension works fine.

## Actual Behavior
There is no "Block this site" anywhere on Bing search results.

## Steps to Reproduce the Problem

1. Have the new Bing experience, but keep using the standard seach (not chat)
2. Search for something on https://www.bing.com
3. There's no "Block this site" anywhere

## Specifications

- Browser: Edge 110.0.1587.41 (Official build) (64-bit)
- Other extensions/add-ons: none

- Browser: Firefox 110.0 (64-bit)
- Other extensions/add-ons: none

- Search engine: www.bing.com
- Language: English (US)
- Region: UK
![image](https://user-images.githubusercontent.com/30084738/219467965-35fd7084-33d1-46a3-ad9f-7913dbd40c5d.png)
![image](https://user-images.githubusercontent.com/30084738/219468082-c53b17f4-db7b-41a1-82cf-eb131408610b.png)

**Comment by iorate** [comment]
@maxcurzi Please wait until I have access to the new Bing; I'm still on the waitlist.

If possible, can you tell me the DOM structure of the result page as in https://github.com/iorate/ublacklist/issues/301#issuecomment-1353837819 ?

**Comment by maxcurzi** [comment]
> @maxcurzi Please wait until I have access to the new Bing; I'm still on the waitlist.
> 
> If possible, can you tell me the DOM structure of the result page as in [#301 (comment)](https://github.com/iorate/ublacklist/issues/301#issuecomment-1353837819) ?

Hi, I'm not sure how to extract this information like that comment.
I opened the dev tool (F12), in Elements right click just below <!DOCTYPE html> and "copy element".
But it doesn't look anything like that structure: https://gist.github.com/maxcurzi/ec4dc72afe8170199998ce7feb20c24c

Let me know if there's a better way to extact it

**Comment by maxcurzi** [comment]
@iorate If it helps I noticed that the issue is there in both regular and incognito mode (with only uBlacklist active). In incognito mode I don't have access to the "new" Bing.

**Comment by iorate** [comment]
Thanks.

The DOM structure that you uploaded seems similar to that of the current (old) version of Bing, but it does not expose real URLs of search results, that is, links point to URLs beginning with `https://www.bing.com/`. Obviously such links cannot be blocked by URL.

At least, in the current version of Bing and Firefox/Edge, this behavior can be disabled by turning off "Open links in new tab". Can you change this option somewhere (in the settings page)?

**Comment by maxcurzi** [comment]
It worked! Thank you so much, I'll close this issue.

![image](https://user-images.githubusercontent.com/30084738/219958109-608cc7b8-6e7c-40f8-b47c-3c21325b2201.png)

For posterity: the "open links in new tab" is not in Edge's preferences, but it was specific to Bing and it's accessed here:
![image](https://user-images.githubusercontent.com/30084738/219958283-8451efdb-1fef-4417-8f5f-db632399de8c.png)

**Comment by kklot** [comment]
Turning off open in new tab still not work for me, I use Vivaldi (which by pass bing restriction on bing chat if that is still the case)

```
Vivaldi	6.1.3035.302 (Stable channel) (arm64) 
Revision	773772e7e92bf14ad0c8f85f41e3d133d0a2b876
OS	macOS Version 13.0.1 (Build 22A400)
JavaScript	V8 11.4.183.29
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Command Line	/Applications/Vivaldi.app/Contents/MacOS/Vivaldi --flag-switches-begin --enable-features=ui-debug-tools --flag-switches-end --origin-trial-disabled-features=WebGPU --disable-smooth-scrolling --save-page-as-mhtml
Executable Path	/Applications/Vivaldi.app/Contents/MacOS/Vivaldi
Profile Path	/Users/knguyen/Library/Application Support/Vivaldi/Default
Linker	lld

```
