### ISSUE TITLE
Can this extension is acced my saved id and password ? Does it collects my id and password and send to some analysis ?

### ISSUE THREAD

**Issue by pspatel602** [iorate/uBlacklist#32]
## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - OS:
  - Browser:
  - Other extensions that might interfere:

**Comment by iorate** [comment]
> Can this extension is acced my saved id and password ?

Yes partially. It CAN access GMail addresses and usernames displayed on Google SERP, but DOES NOT.

> Does it collects my id and password and send to some analysis ?

No.
