### ISSUE TITLE
Pinterest is slipping past the blockade again, with no option to block the site

### ISSUE THREAD

**Issue by landshrk** [iorate/ublacklist#321]
## Expected Behavior

`*://*.pinterest.com/*` entry will block all instances of pinterest from showing up in search results.

## Actual Behavior

Pinterest shows up in at least one search, with no option to block/remove it from the results. See screenshots here:

https://i.imgur.com/qXaf6Ag.png

https://i.imgur.com/zznXZ7R.png

Note that the results above and below the ~~offending garbage~~ pinterest results are both able to be blacklisted. 

## Steps to Reproduce the Problem

1. Search for any of seemingly random things, like aftermarket watch straps, and cat ceramics, but not modern barn decor, using Google (signed in), using Firefox, on Windows 11. 
   - I was not able to make any sense of which searches triggered the behavior, and which did not. I will test further with Windows 10 and Linux to see if there's any effect there. Will post results below if there's anything of note.
2. Doing the same in a non-signed in Google in a private browsing window yields the same results

## Specifications

- Browser: Firefox
- Other extensions/add-ons: Lots, but the issue is present when uBlacklist is the only active extension, as evidenced with the private browsing results listed above. 
- Search engine: Google
- Language: English
- Region: US

**Comment by landshrk** [comment]
Issue is present on a Windows 10 machine with a few more blocks added, and (importantly for this issue) a slightly different Pinterest block: 

- *://www.pinterest.com/*

**Comment by mrtwebdesign** [comment]
Everything is slipping past. This happened after Chrome V 110 update.
I think Chrome changed their api.

**Comment by landshrk** [comment]
Fair, that does seem to be a thing that Google is going for, removing control from its end users (see also their gelding of adblocking that's coming down the pipe sooner than later). 

But I'm on Firefox. Would this still affect FF/non-Chrome users?

**Comment by 4N7** [comment]
If you want to use a mainstream engine, I suggest the [LibreWolf](https://librewolf.net/) branch of Firefox.

If you must use Google’s browser, maybe you can still filter search results with a [uBlock Origin](https://ublockorigin.com/) filter. Here’s a useful tool for generating rules: https://letsblock.it/filters/search-results
