### ISSUE TITLE
The "block this site" link not appearing on certain google searches

### ISSUE THREAD

**Issue by drianared** [iorate/ublacklist#322]
## Expected Behavior

block this site link should appear on all google search results

## Actual Behavior

block this site link appears on only certain google search results

## Steps to Reproduce the Problem

1.  google search apples
2.  block this site link appears
3. google search hdd
4. block this site links do not appear

## Specifications

- Browser: google chrome latest version
- Other extensions/add-ons:

- Search engine:
- Language:
- Region:

**Comment by iorate** [comment]
Not enough information has been provided, but I expect this will be fixed in v8.2.6.
