### ISSUE TITLE
[Feature enhancement] Add longer update interval

### ISSUE THREAD

**Issue by throwaway-d** [iorate/ublacklist#326]
At the moment, the maximum update interval is 1 day. But all subscriptions I know are very super rarely updated. And I wish to have longer interval, example:

- 1 week
- 2 weeks
- 1 month
- 2 months
- 6 months
- 1 year

Why do I want that? Because I want to save their code hosting platform's bandwidth and traffic speed. Especially my own [filter list](https://codeberg.org/Recommendations/wikivncopy) that is hosted on Codeberg and Codeberg has smaller infrastructure than GitHub.

**Comment by lyaaz** [comment]
This makes no sense unless #307 implemented (or you never restart your browser)

**Comment by throwaway-d** [comment]
> unless https://github.com/iorate/ublacklist/issues/307 implemented

Do you mean _**un**implemented_

**Comment by lyaaz** [comment]
yes

**Comment by throwaway-d** [comment]
So if the update interval is ignored on every startup, the update interval's existence is pointless. And what is the point of user's choice? Users should have their own choice. And updating on every single startup ever will take lots of bandwidth. **#307 should be unimplemented**

**Comment by throwaway-d** [comment]
- https://adguard.com/en/blog/easylist-filter-problem-help.html
- https://www.techradar.com/news/your-adblocker-could-be-facing-a-potentially-big-traffic-problem
