### ISSUE TITLE
filters need www

### ISSUE THREAD

**Issue by nicoleahmed** [iorate/ublacklist#329]
## Expected Behavior
that the two filters below:
*://www.attractiongym.com/*
*://attractiongym.com/*

I believe both should filter out any results for the attractiongym.com when putting the following search into Google:
help "attractiongym.com"

## Actual Behavior
Only *://www.attractiongym.com/*   filters results
This filter doesn't work - *://attractiongym.com/*

Other domains affected:
nstec.com
eehelp.com
compuhoy.com
nhsdiscounts.org.uk
branddiscount.co.uk
nhsdiscounts.co
nhsdiscountcode.co.uk
student-discount.co.uk
bestbikeguide.co.uk
thenina.com

## Specifications
- Browser: Firefox
- Other extensions/add-ons: UBO

Thanks

**Comment by nicoleahmed** [comment]
I've solved this by changing lines that start with  
*://www or *://  
to  
*://*.

Suggest that an option be provided at blocking time to do this from search results and webpages

**Comment by iorate** [comment]
![option](https://user-images.githubusercontent.com/682043/228264265-d1f49d18-3c4e-4155-b85e-9f08644a0356.png)
