### ISSUE TITLE
The "block this site" link not appearing on google searches

### ISSUE THREAD

**Issue by lovebaicai** [iorate/ublacklist#333]
OS version: macOS 12.6.3 (Intel Core)
Browser version: chrome 111.0.5563.146
Extensions version: 8.2.6
Screenshot: ![Snipaste_2023-03-28_18-13-27.png](https://s2.loli.net/2023/03/28/F6vbSJu5DigAKVH.png)

**Comment by Bowtiebearer** [comment]
Same problem, same version on Brave. OS is Windows 11

**Comment by numpad0** [comment]
Same on Firefox, must be Google changes

**Comment by Asnacinjar** [comment]
same problem, please update

**Comment by Bowtiebearer** [comment]
Also some sites are not being blocked despite the list

**Comment by YourFriendlyError** [comment]
The new update semi works. It does not block blacklisted sites entirely.
![image](https://user-images.githubusercontent.com/41340245/228695059-20ffa95b-9a5b-4a97-88e3-38dc77021002.png)

**Comment by talizea** [comment]
Not seeing "block this site" on the news tab anymore (checked on both firefox and chrome). Works fine in the regular search and images etc.
