### ISSUE TITLE
It does not work sometimes.

### ISSUE THREAD

**Issue by suno2015** [iorate/ublacklist#334]
<img width="754" alt="image" src="https://user-images.githubusercontent.com/60562136/228267739-664b4659-73d1-48db-bd8b-b3376cee04fb.png">
<img width="741" alt="image" src="https://user-images.githubusercontent.com/60562136/228267848-d3f6b0f4-1b94-4c39-88f0-a3936dfc30ec.png">

**Comment by iorate** [comment]
duplicate of #333 ?
