### ISSUE TITLE
Broken on Google with Safari 16.2

### ISSUE THREAD

**Issue by rickwierenga** [iorate/ublacklist#336]
## Expected Behavior

Extension works

## Actual Behavior

The extension does not show the "block site" button on Google.

## Steps to Reproduce the Problem

-

## Specifications

- Browser: Safari 16.2
- Other extensions/add-ons: AdGuard

- Search engine: Google
- Language: English
- Region: Netherlands

**Comment by HoneyLuka** [comment]
The new version 8.2.7 has been released. Please update to the latest version. It should fix this.

**Comment by rickwierenga** [comment]
Awesome, thanks!
