### ISSUE TITLE
[Japanese] "このサイトをブロックする" ("Block this site") is rendered with Chinese font for Chinese websites on Google search

### ISSUE THREAD

**Issue by Phroneris** [iorate/ublacklist#337]
日本語での使用時の話なので、日本語で書きます。

## Expected Behavior

- Google検索結果ページの各項目にある「このサイトをブロックする」が、いずれも日本語フォントで表示されるはず。

## Actual Behavior

- Google検索結果ページの各項目にある「このサイトをブロックする」が、基本的には日本語フォントで表示されるものの、中国語のサイトの場合には中国語フォントで表示される。

## Steps to Reproduce the Problem

1. uBlacklistの『「このサイトをブロックする」リンクを非表示にする』オプションを切る。
1. 例えば「weibo」とGoogle検索する。

![uBlacklist-text-chinese](https://user-images.githubusercontent.com/9891867/228814271-ed005259-bf4d-432b-9d9a-a61370751e28.png)

各検索結果はそれぞれの言語に対応した `lang` 属性を持っており、それに影響されるのが原因かと。
なお、Google自身が追加しているはずの「このページを訳す」も同じ影響を受けてますけどね…。

## Specifications

- OS: Windows 10
- Browser: Chrome 111.0.5563
- Other extensions/add-ons: 色々入れていますが、全て切ってシークレットモードで閲覧しても同じでした。
- Search engine: Google
- Language: Japanese/日本語
- Region: Japan/日本

**Comment by iorate** [comment]
「このサイトをブロックする」に `lang` 属性を付けました。
「このページを訳す」には関知しません。
