### ISSUE TITLE
Localization of the description of the extension in the "details" tab

### ISSUE THREAD

**Issue by Fikafusik** [iorate/uBlacklist#34]
**Hello, thanks for your work!**

I do not understand browser extensions. Is it possible to localize the description of the extension in the "Details" tab (I use **firefox** browser)? I found the description text in chrome-web-store/en/description.txt. Need to create a similar file in the chrome-web-store/ru folder?

![details](https://user-images.githubusercontent.com/26993664/77851410-ba930900-71e1-11ea-91ab-cb994b693f10.jpg)

**Comment by iorate** [comment]
Thank you for your contribution.

The description of the extension can be localized.
If you translate the description into Russian and save it as `web-store-assets/ru/description.txt` (I renamed the folder just now), I will upload it to Firefox Add-ons and Chrome Web Store manually.

**Comment by Fikafusik** [comment]
#35

**Comment by iorate** [comment]
Thank you. I've uploaded the Russian description to the web stores.
