### ISSUE TITLE
Can't filter properly when using auto flip

### ISSUE THREAD

**Issue by QiXing1217** [iorate/ublacklist#344]
## Expected Behavior
When using automatic page turning, search results can be filtered normally
## Actual Behavior
When using automatic paging, the search results are not properly filtered
## Steps to Reproduce the Problem

1.Install this tampermonkey script(https://greasyfork.org/scripts/419215-%E8%87%AA%E5%8A%A8%E6%97%A0%E7%BC%9D%E7%BF%BB%E9%A1%B5/code/%E8%87%AA%E5%8A%A8%E6%97%A0%E7%BC%9D%E7%BF%BB%E9%A1%B5.user.js)
1.Do a google search (choose keywords that are easy to intercept)
1.Successfully reproduced
When the page is not turned automatically (normal search situation, everything is ok)
![image](https://user-images.githubusercontent.com/124881213/236681178-56bf12e7-bab5-486a-867e-88dccbcbf99d.png)
There was a problem after the automatic page turning, and the results of subsequent loading were not successfully filtered (guessing that such a situation was not considered)
![image](https://user-images.githubusercontent.com/124881213/236681283-abe2b545-e1c9-459d-b6c3-8cc4d04f28b1.png)
![image](https://user-images.githubusercontent.com/124881213/236681257-3b4e1964-a824-4730-ba39-acc6483590e1.png)

## Specifications

- Browser:Chrome 113.0.5672.63
- Other extensions/add-ons:tampermonkey uBlacklist

- Search engine:google
- Language:中文
- Region:台湾

**Comment by iorate** [comment]
DUPLICATED
https://github.com/iorate/ublacklist/issues/266#issuecomment-1229362937
