### ISSUE TITLE
Website blocking does not work regarding Google News (+ headlines in main search)

### ISSUE THREAD

**Issue by MaxVonMustermann** [iorate/ublacklist#345]
## Expected Behavior
Filtered websites are not supposed to show up in the "News" category of Google (news.google.com) nor the headlines rubric that are also shown in the main search.

## Actual Behavior
Filtered websites show up both as headline sources in the main search and as part of Google's news feed (news.google.com).

## Steps to Reproduce the Problem

1. Add website to filter list
2. Search for a certain topic (and also add the blocked website to make search more precise)
3. Find out that blocked website is still visible. Sometimes not on the first news search result page, but on later pages.

## Specifications

- Browser: Safari, Microsoft Edge
- Other extensions/add-ons: /

- Search engine: Google
- Language: German
- Region: Germany

**Comment by opensorceror** [comment]
Hi, thank you for this awesome app! Is there also a plan to add this fix in the iOS and iPadOS apps? I still see news results from blocked websites on mobile.

**Comment by HoneyLuka** [comment]
> Hi, thank you for this awesome app! Is there also a plan to add this fix in the iOS and iPadOS apps? I still see news results from blocked websites on mobile.

In iOS, The latest version is 8.3.3 you can update and try it again. It works fine for me.

**Comment by opensorceror** [comment]
@HoneyLuka thanks for your response. I am on 8.3.3 but I’m still experiencing this issue. See attached screenshot- I blocked `*://www.forbes.com/*` and uBlacklist does hide search results, but not news results.

![IMG_2323](https://github.com/iorate/ublacklist/assets/10184251/985bfc1b-76c3-4c27-b7ca-9f4356fe3b63)

**Comment by HoneyLuka** [comment]
@opensorceror Sorry, I didn't reproduce this problem according to your operation. It works fine for me. Maybe this is related to Google's different style in different regions?
![image](https://github.com/iorate/ublacklist/assets/4635725/82746279-ec65-47f3-8e57-2d930a20df40)
