### ISSUE TITLE
Extension broken in DuckDuckGo

### ISSUE THREAD

**Issue by test6678** [iorate/ublacklist#346]
Blocking search results no longer works in DuckDuckGo. Other search engines (Google, Yandex, etc.) seem to be unaffected.

**Comment by ghjb004** [comment]
Also not working on DuckDuckGo in Safari, I am not sure if this is a separate issue. 
Is there a Safari update on the way?

**Comment by AnityEx** [comment]
not working on edge, just downloaded toady for this and i come here and see its not working lol

**Comment by 1Phase1** [comment]
Can confirm it's not working on DuckDuckGo on Firefox.

**Comment by parapacem** [comment]
DuckDuckGo IMAGE, VIDEO and NEWS all working, not web search though
Yandex browser, have tried two devices both using Windows 10

**Comment by MediaEU** [comment]
Is this not strange that no one has at least an assumption why it doesn't work anymore? Debian/Chrome Version 105.0.5195.125 (Official Build) (64-bit)

**Comment by bunnyhero** [comment]
if i had to guess, duckduckgo probably changed their CSS or something like that.

**Comment by ghjb004** [comment]
as of today the "block this site" button is showing in the Safari DDG images and videos tabs but not the "all results" tab.
Blocked sites appear to be blocked in those tabs but not in the "all results tab. Can other users can confirm this?

**Comment by SaunaThenColdBath** [comment]
@ghjb004 I'm using the extension on Firefox. I confirm the same behavior. The filter is not working on All result tab, and no 'block this site' button. However, the button is shown on Images, News, Video tab.

**Comment by KirkH420** [comment]
Not working for me in on DDG either.

**Comment by ghjb004** [comment]
iorate様　お願い致します！

**Comment by Jon-guy30** [comment]
This extension is not updated in firefox AMO. Is the 8.3.1 version going to be released there?

**Comment by ghjb004** [comment]
Just installed the Safari update. Many thanks, working again.
