### ISSUE TITLE
[Enhancement] Import name from list automatically

### ISSUE THREAD

**Issue by SocietasEvanescentes** [iorate/ublacklist#351]
Similar to that of AdBlock lists, I think it would be great if when adding custom subscriptions, uBlacklist could understand and apply names automatically to them.

It would look for **! Name/Title** and apply it to the "name" box.

AdBlock example:

> ! **Title: 🔮 I Don't Want to Download Your Browser**
> ! Version: 24May2023v1-Beta
> ! Expires: 5 days

**Comment by iorate** [comment]
Version 8.8 or later supports YAML frontmatter and imports the `name` field.

```
---
name: Example
---
*://*.example.com/*
```
