### ISSUE TITLE
No longer works on Google Image results

### ISSUE THREAD

**Issue by starfyre-wolf** [iorate/ublacklist#352]
## Expected Behavior
Websites on my blocklist should not show up in image results. 

## Actual Behavior
Blocked websites still show up in Google Image results. The "block this website" button is also missing. Fandom.com is on my blocklist.
![Screenshot (1)](https://github.com/iorate/ublacklist/assets/139395090/65f13059-8c63-49a7-8706-1dc4f3a90949)

## Steps to Reproduce the Problem

1. Enter a search into Google
2. Add a website via Web results
3. View Image results and look for the blocked website

## Specifications

- Browser: Google Chrome v.114.0.5735.199
- Other extensions/add-ons: uBlock Origin, Leechblock NG

- Search engine: Google
- Language: English
- Region: United States

**Comment by brysont** [comment]
I can second this as of today (worked fine yesterday).

- Chrome Version 114.0.5735.199 (Official Build) (64-bit)
- Opera GX LVL5 (core: 100.0.4815.44) - Chromium Version 114.0.5735.199
- Neither updated in the past 48 hours

Not just this extension, but also "Search Filter" in the Chrome Store. Zero on-page functionality, though settings and all still work.
