### ISSUE TITLE
ublacklist 8.3.2

### ISSUE THREAD

**Issue by Alex-Mirov** [iorate/ublacklist#354]
Hello

ublacklist 8.3.2 version is not showing on firefox addon page, only up to 8.3.1 . 

thanks

**Comment by iorate** [comment]
v8.3.2 was rejected by a Mozilla reviewer.
I uploaded v8.3.2.1 with updated build instructions.

**Comment by iorate** [comment]
v8.3.2.1 is now available on AMO. There are no changes between v8.3.2 and v8.3.2.1.
