### ISSUE TITLE
Match pattern rules are case sensitive

### ISSUE THREAD

**Issue by NotaInutilis** [iorate/ublacklist#356]
## Expected Behavior
*://*GITHUB.COM/* = *://*github.com/*

## Actual Behavior
*://*GITHUB.COM/* ≠ *://*github.com/*

## Steps to Reproduce the Problem

I specifically tried this for the Pinterest Microsoft app on Google. The two following rule `*://*.microsoft.com/*9PFHDSF91B9R*` gets this result.

![Screenshot 2023-08-07 at 01-01-56 pinterest microsoft - Recherche Google](https://github.com/iorate/ublacklist/assets/9675966/4c5f0189-bc73-43ec-9397-804591b6eacf)

Switching to lowercase `*://*.microsoft.com/*9pfhdsf91b9r*` switches which entry is blocked and which one is not.

## Specifications

- Browser:  Firefox 116.0.1
- Other extensions/add-ons: Too many.

- Search engine: Google
- Language: FR
- Region: FR

**Comment by e-t-l** [comment]
Ublacklist uses RegExp, so you can add `i` after your ending slash to make it case-insensitive. (I do agree it would be nice if the code added this modifier in the backend though) 

https://learn.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-options

**Comment by NotaInutilis** [comment]
Thanks for the input! I'm not that familiar with regex. Are these match patterns a type of regex? These pattern don't seem to end with a slash so should I add one? Or rewrite them in regex? Sorry for the question dump, the match pattern documentation I found does not say anything about regex.

It would indeed be nice if it was automatically added to match pattern entries as these are more likely to be used by regular users with no knowledge of regex rules and specificities (such as myself)

**Comment by iorate** [comment]
Works as expected; the *path* part of the match pattern is intentionally case-sensitive, as the *path* part of URLs is often case-sensitive.

> Actual behavior.
> \*://GITHUB.COM/ ≠ \*://github.com/

This is incorrect. The *host* part of the match pattern is case-insensitive.

To block URLs containing the ID of Pinterest app, add the following simple rule:
`/9pfhdsf91b9r/i`

**Comment by NotaInutilis** [comment]
Ok, my bad! I indeed didn't test the host part and jumped to conclusions. Thanks for explaining and giving the solution.
