### ISSUE TITLE
[FEATURE] Add a whitelist toggle

### ISSUE THREAD

**Issue by ghost** [iorate/ublacklist#358]
I am a big fan of whitelists, as I created a regex pattern to do it for me in your extension
`/^((?!google.com|youtube.com|wikipedia.org|amazon.com|archive.org).)*$/i`

However this is cumbersome, I would like you to add a switch, if **not** in the list, block.

I could block every website I don't like, but the list of websites I want shown is a smaller list than the websites I don't want shown.

I *hate* aggressive SEO tactics, scam websites, PC Support websites, etc, and I want this to be right alongside PopUpOFF in my extension powerbox of Firefox.

**Comment by iorate** [comment]
You can subscribe to a list containing `*://*/*` to emulate a whitelist mode.
