### ISSUE TITLE
[Question/Discussion] Using uBlacklist subscriptions and function with uBlock Origin

### ISSUE THREAD

**Issue by jessienab** [iorate/uBlacklist#359]
I am just wondering if there's a way to have uBlock Origin act in a similar way to uBlacklist, as in, to block elements on a page based on provided filters (similar to the My Filters section in uBO, using the zapper or dropper tool).

I can import subscription lists by changing the `*` elements at start and endlines, to `||` and `^`, which allows importing to My filters, but that only stops those pages from loading if access is attempted.

I am only asking just to try and keep the number of extensions I use low... however I recognize this is maybe a stupid question since the whole purpose of uBlacklist is to remove the elements.

Thanks!

**Comment by NotaInutilis** [comment]
Yep, it's possible, there's a tool for that here https://letsblock.it/filters/search-results

It also references the uBlock-Origin-dev-filter "Filters to block and remove copycat-websites from DuckDuckGo, Google and other search engines." https://github.com/quenhus/uBlock-Origin-dev-filter

However, according to https://letsblock.it/filters/search-results, uBlacklist more efficient than uBO regarding search engine filtering and covers more services (Bing, Brave, DuckDuckGo, Ecosia, Qwant, Searx, Startpage.com, Yahoo! JAPAN and Yandex).

> Due to technical limitations, this template has lower performance and compatibility than dedicated extensions such as uBlacklist. We suggest testing this extension if you need compatibility with search engines we don't support, such as Bing.
