### ISSUE TITLE
[Major Bug] Incomplete Blocking and Missing 'Block This Site' Option on Many Google Search Results

### ISSUE THREAD

**Issue by georgekolasa** [iorate/ublacklist#360]
## Expected Behavior
Blocking every link that's is supposed to be blocked. And displaying a "Block This Site" option next to each search result not blocked (esp if the "Block This Site" links are not set to "hidden" in the extension settings).

## Actual Behavior
It's blocking some of the search results that should be blocked, but not all. As an example, these results should all be blocked but they are not: https://i.gyazo.com/a9d7d06ae19d2be99ddf9444b1034b93.png

This only started like a few weeks ago (roughly 3 weeks ago if I had to precisely guess). Not sure if google changed something in their layout/selectors or if [commit 00a1af1](https://github.com/iorate/ublacklist/commit/00a1af119d82b8245a7980c47ba7b34dc62702bc) possibly messed it up for some news site results.

## Steps to Reproduce the Problem

1. As an example, search "sbf jail" in Google  (or visit [this URL](https://www.google.com/search?q=sbf+jail&safe=strict&sca_esv=560574176&sxsrf=AB5stBilPT7A0VHpWG7V0yzKab3aofIAeA%3A1693192088447&ei=mA_sZLPwGpuf5NoPzs6LmAE&ved=0ahUKEwiznN-HsP6AAxWbD1kFHU7nAhMQ4dUDCBA&uact=5&oq=sbf+jail&gs_lp=Egxnd3Mtd2l6LXNlcnAiCHNiZiBqYWlsMgQQABhHMgQQABhHMgQQABhHMgQQABhHMgQQABhHMgQQABhHMgQQABhHMgQQABhHSL0GUI8DWI8DcAB4A5ABAJgBAKABAKoBALgBA8gBAPgBAeIDBBgAIEGIBgGQBgg&sclient=gws-wiz-serp#ip=1))
2. Block every single news site you see
3. See that some of them are unblockable/don't have the "Block This Site" link next to them. [Link to image of this issue as well. ](https://i.gyazo.com/a9d7d06ae19d2be99ddf9444b1034b93.png)

## Specifications

- Browser: Vivaldi
- Other extensions/add-ons: I disabled all of them except ublacklist and still have this issue.

- Search engine: Google
- Language: English
- Region: New York, USA

@iorate

**Comment by georgekolasa** [comment]
@iorate

**Comment by daggilli** [comment]
The extension is completely non-functional on Google videos (browsers Chrome 116.0.5845.110 and Brave 1.57.53 Chromium: 116.0.5845.114, both 64-bit builds on Ubuntu 20.04)
