### ISSUE TITLE
ublacklist doesn't work in firefox (desktop browser)

### ISSUE THREAD

**Issue by Druout** [iorate/ublacklist#361]
## Steps to Reproduce the Problem

1. Install firefox
1. Install ublacklist extension
1. search anything and watch no ublacklist block site text/option appear at all next to sites

## Specifications

- Browser: Firefox
- Other extensions/add-ons: None

- Search engine: Duckduckgo
- Language: English
- Region: US

**Comment by NickNothom** [comment]
The extension appears to be totally broken in Firefox. Any suggestions?
