### ISSUE TITLE
Should my subscription be removed from the list?

### ISSUE THREAD

**Issue by throwaway-d** [iorate/ublacklist#367]
My `wikivncopy` subscription was added in https://github.com/iorate/ublacklist/pull/315
https://iorate.github.io/ublacklist/subscriptions#vietnamese
Now I decided to archive it. Should it be removed from the list?

**Comment by iorate** [comment]
I think so, but do as you like.

**Comment by throwaway-d** [comment]
> do as you like

So I think I should archive this.

**Comment by throwaway-d** [comment]
Did you remove it yet?
