### ISSUE TITLE
Certain sites are not completely blocked

### ISSUE THREAD

**Issue by miso-nikomi-nasu** [iorate/ublacklist#369]
## Expected Behavior

completely blocked

## Actual Behavior

Certain sites are not completely blocked

## Steps to Reproduce the Problem

1.Add youtube tiktok to the chrome version of uBlacklist filter
1.use google search
1.YouTube and TikTok are displayed in the search results, although only a few.
(This function is based on google search, and uBlacklist may not be related.)

## Specifications

- Browser:chrome
- Other extensions/add-ons:

- Search engine:Google
- Language: japanese
- Region: japanese

**Comment by iorate** [comment]
I'm not able to reproduce this issue yet.

**Comment by miso-nikomi-nasu** [comment]
If you add video sites such as YouTube or TikTok to your block list, they will be blocked to some extent.

https://i.postimg.cc/FRWN7mDg/youtube-google02.png
https://i.postimg.cc/9QVtQjSn/youtube-google.png
https://i.postimg.cc/wM7JsfVn/tiktok-google.png
As you can see in this image, there are some things that can be displayed in search results without being blocked.
(For clarity, search results for [The Parade of the Wooden Soldiers] on youtube tiktok)

The youtube tiktok line displayed in the search results has a feature that there is no switch to add this site to the block list.

ublacklist is working to some extent. Could it be a feature of Google search?

**Comment by iorate** [comment]
The problem is that video results appended later are not filtered, and can be easily fixed. Thank you for your report.
