### ISSUE TITLE
Why sync isn't supported on Firefox for Android?

### ISSUE THREAD

**Issue by lilydjwg** [iorate/uBlacklist#37]
When I first discovered the sync feature, I was thinking: that's great so I can sync my blacklist with my phone. But it turned out that the sync options are hidden on Firefox for Android.

Is there some technical issues to sync on Firefox for Android? (I looked up the issues, the source code and commit history but didn't find anything.)

**Comment by ncaq** [comment]
@lilydjwg 
You can use the "Subscribe" function as a temporary workaround.
You can write a file on GitHub and subscribe to a text file from Firefox for Android.
However, this extension doesn't seem to work on the current Android version of Google.

**Comment by lilydjwg** [comment]
I see, thanks.

**Comment by iorate** [comment]
@lilydjwg 
> Is there some technical issues to sync on Firefox for Android?

Yes. The sync feature requires [browser.identity.launchWebAuthFlow](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/identity/launchWebAuthFlow) to authorize the extension to access Google Drive, but it is not available on Firefox for Android.
