### ISSUE TITLE
Discussions and Forums not filtered

### ISSUE THREAD

**Issue by Rapptz** [iorate/ublacklist#376]
## Expected Behavior

Discussions and Forums items are filtered if URLs match. In this case the URL is `*://www.quora.com/*`.

## Actual Behavior

They're not.

![image](https://github.com/iorate/ublacklist/assets/1695103/c9d51d9e-9f38-4bb1-8426-8c3b16877344)

## Steps to Reproduce the Problem

1. Search for something on https://google.com
1. Scroll down

## Specifications

- Browser: Firefox
- Other extensions/add-ons: N/A

- Search engine: Google
- Language: English
- Region: America

## Other Info

I wouldn't mind opening a PR for this, but I'm unsure how to filter it or how to get started. These results seem relatively rare, it's my first time seeing this heading at all so it's no surprise it's not filtered. The DOM for it is as follows:

<details>
<summary>DOM of the above screenshot</summary>
<pre>
&lt;div class=&quot;Ww4FFb vt6azd&quot; data-hveid=&quot;CFMQAA&quot;&gt;
  &lt;div class=&quot;qtOtne gVrOEd&quot;&gt;
    &lt;div class=&quot;RES9jf IFnjPb&quot; aria-level=&quot;2&quot; role=&quot;heading&quot;&gt;Discussions and forums&lt;/div&gt;
  &lt;/div&gt;
  &lt;div&gt;
    &lt;div&gt;
      &lt;div class=&quot;LJ7wUe gVrOEd&quot;&gt;&lt;a class=&quot;v4kUNc&quot;
          href=&quot;https://www.reddit.com/r/funny/comments/ldovzf/haribo_diarrhea_squirts/&quot; data-jsarwt=&quot;1&quot;
          data-usg=&quot;AOvVaw3N9ZUfByhWLxkXZGlt36Qy&quot; data-ved=&quot;2ahUKEwjR1amP-tiCAxUaomoFHftND6wQzLMHegQIQhAB&quot;
          data-jrwt=&quot;1&quot;&gt;
          &lt;div&gt;
            &lt;div class=&quot;YmM2gd&quot;&gt;
              &lt;div&gt;
                &lt;div class=&quot;zNWc4c&quot; aria-level=&quot;3&quot; role=&quot;heading&quot;&gt;
                  &lt;div class=&quot;r0uZsf&quot; role=&quot;link&quot;&gt;HARIBO Diarrhea Squirts : r/funny - Reddit&lt;/div&gt;
                &lt;/div&gt;
                &lt;div&gt;
                  &lt;div&gt;
                    &lt;div class=&quot;iDBaYb&quot;&gt;
                      &lt;div class=&quot;d6R6kf&quot;&gt;
                        &lt;div&gt;
                          &lt;div class=&quot;oRVWZ Vwoesf&quot; aria-hidden=&quot;true&quot;&gt;&lt;img class=&quot;XNo5Ab&quot;
                              src=&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAASFBMVEVHcEz/RQD/RQD/RQD/RQD/RQD/RQD/RQD/RQD/RQD/RQD/RQD/NAD/PwD/aDr/s5z/nH7/e1b/WyT/xLH/imj/4NX/8ev///9xkjBnAAAADHRSTlMAFFyk2vT9KO//iszHtZsMAAABSElEQVR4AWxSB7aDMAxjg6md7XD/m35s/PqTtmJkSImUMfxjnOZl3bZ1madx+MY+H/DGMe8f9Hiu0GE9x274C77w2hu+mb3x2X/zSDeQGsXYzk/Oh5hiLiQuT44TGlDgzFyvmkRxqsHaCXJASnxdTgSrmMzQgR2JTyQQzHeCLiE51oLIVjIOU0sTloxGPpjUQTkgcMEz+5KIpG0ei9IQHRa+DBwxOVDJMqzqXO/eqwHf77OOYZPN89pb68Na4fGmtkZQY9LSp1IbgW6Tk56MlIQAwix6s9CQWMQ3YRBBQZA8ATXks0yK6mE5WctCukzbqFSvHuYAk201BekLOpSDqD3ZVttWkpeYyZXiUpYqmMP7uFHHVWYtJKEed3NhKAUhReTFX3B2V44IXCwlOiDjX+PnpSUFGP6GK1kj5AllHEJZj8jMSzD7AwBb/yl65xYVzAAAAABJRU5ErkJggg==&quot;
                              style=&quot;height:16px;width:16px&quot; alt=&quot;&quot; data-csiid=&quot;43&quot; data-atf=&quot;1&quot;&gt;&lt;/div&gt;
                        &lt;/div&gt;
                      &lt;/div&gt;
                      &lt;div class=&quot;LbKnXb YAG2qc&quot;&gt;
                        &lt;div class=&quot;R8BTeb q8U8x OSrXXb&quot;&gt;Reddit&lt;/div&gt;
                        &lt;div class=&quot;xuPcX yUTMj OSrXXb al4kQ&quot;&gt;r/funny &middot; 10+ comments &middot; 2y&lt;/div&gt;
                      &lt;/div&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
        &lt;/a&gt;&lt;/div&gt;
      &lt;div class=&quot;LJ7wUe iKLTkb gVrOEd&quot;&gt;&lt;a class=&quot;v4kUNc&quot;
          href=&quot;https://www.quora.com/Do-Haribo-sugar-free-gummy-bears-really-give-you-diarrhea&quot; data-jsarwt=&quot;1&quot;
          data-usg=&quot;AOvVaw3EO1qpHKjenOY3RLfkEpwW&quot; data-ved=&quot;2ahUKEwjR1amP-tiCAxUaomoFHftND6wQzLMHegQIThAB&quot;
          data-jrwt=&quot;1&quot;&gt;
          &lt;div&gt;
            &lt;div class=&quot;YmM2gd&quot;&gt;
              &lt;div&gt;
                &lt;div class=&quot;zNWc4c&quot; aria-level=&quot;3&quot; role=&quot;heading&quot;&gt;
                  &lt;div class=&quot;r0uZsf&quot; role=&quot;link&quot;&gt;Do Haribo sugar free gummy bears really give you diarrhea? - Quora
                  &lt;/div&gt;
                &lt;/div&gt;
                &lt;div&gt;
                  &lt;div&gt;
                    &lt;div class=&quot;iDBaYb&quot;&gt;
                      &lt;div class=&quot;d6R6kf&quot;&gt;
                        &lt;div&gt;
                          &lt;div class=&quot;oRVWZ Vwoesf&quot; aria-hidden=&quot;true&quot;&gt;&lt;img class=&quot;XNo5Ab&quot;
                              src=&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAABuElEQVR4AWIYcmAUAIitVtiGYSDKAsJBFK6zZPOCaCBc4zgwcFzF5ZwDqwqXzTkZx9UUWBCNbe+qgmk7X+M428BTK/vO7/l+TrRUA320ZgSOd4y8FrD3i8SmA8k5OlqiMx8iLC2AB7r9iB01wMQEeYAPfEvJD8BFIdIB3+DMoYT8ygeVga4BZ2WSmwZI39yaGb8+WHNiRHv7P6uRsNTkCJgSxG8gGhDW6rsP1qvbHmwSQqbV1S4dECy9Yq995B9gE2GbiES3RsBZurlKLogQI4FU6Y7O1DBcBMchv4jNIM0JdVgFR70QtpnzmyuA6wT+syCi10I3/sy98QXT0wvnjZrDUQj/aauAAF/hvGOmAPpTAUIKyBcI8IKAUXPohQigkKja0AVVFKYjc+htaGmXNgxSGzpuQ1M/Uu4TI7jNeMja4IRBtCadITWK3bpRDNuWbRPjvCt7jBzxrQapJnjtvic/RtZMGfmjRv0Q4cLkCv/yHPPETNmHWwqpyW2hA5D/QSKn7x14VgkVEZf/FtEA044inrZOte4+2ZYiEZZeRIIMITUO+hy8YwJkNxCLgXoLdoIKosEERgEARFUBpYHXWVMAAAAASUVORK5CYII=&quot;
                              style=&quot;height:16px;width:16px&quot; alt=&quot;&quot; data-csiid=&quot;44&quot; data-atf=&quot;1&quot;&gt;&lt;/div&gt;
                        &lt;/div&gt;
                      &lt;/div&gt;
                      &lt;div class=&quot;LbKnXb YAG2qc&quot;&gt;
                        &lt;div class=&quot;R8BTeb q8U8x OSrXXb&quot;&gt;Quora&lt;/div&gt;
                        &lt;div class=&quot;xuPcX yUTMj OSrXXb al4kQ&quot;&gt;4 answers &middot; 4y&lt;/div&gt;
                      &lt;/div&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
        &lt;/a&gt;&lt;/div&gt;
      &lt;div class=&quot;LJ7wUe iKLTkb gVrOEd&quot;&gt;&lt;a class=&quot;v4kUNc&quot;
          href=&quot;https://www.quora.com/It-is-true-that-if-you-eat-a-bunch-of-sugar-free-gummy-bears-that-you-will-suddenly-get-horrible-diarrhea&quot;
          data-jsarwt=&quot;1&quot; data-usg=&quot;AOvVaw2FZi1FizukziIsSP4sp7iL&quot;
          data-ved=&quot;2ahUKEwjR1amP-tiCAxUaomoFHftND6wQzLMHegQISRAB&quot;&gt;
          &lt;div&gt;
            &lt;div class=&quot;YmM2gd&quot;&gt;
              &lt;div&gt;
                &lt;div class=&quot;zNWc4c&quot; aria-level=&quot;3&quot; role=&quot;heading&quot;&gt;
                  &lt;div class=&quot;r0uZsf&quot; role=&quot;link&quot;&gt;It is true that if you eat a bunch of sugar-free gummy bears that you
                    will suddenly get horrible diarrhea? - Quora&lt;/div&gt;
                &lt;/div&gt;
                &lt;div&gt;
                  &lt;div&gt;
                    &lt;div class=&quot;iDBaYb&quot;&gt;
                      &lt;div class=&quot;d6R6kf&quot;&gt;
                        &lt;div&gt;
                          &lt;div class=&quot;oRVWZ Vwoesf&quot; aria-hidden=&quot;true&quot;&gt;&lt;img class=&quot;XNo5Ab&quot;
                              src=&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAABuElEQVR4AWIYcmAUAIitVtiGYSDKAsJBFK6zZPOCaCBc4zgwcFzF5ZwDqwqXzTkZx9UUWBCNbe+qgmk7X+M428BTK/vO7/l+TrRUA320ZgSOd4y8FrD3i8SmA8k5OlqiMx8iLC2AB7r9iB01wMQEeYAPfEvJD8BFIdIB3+DMoYT8ygeVga4BZ2WSmwZI39yaGb8+WHNiRHv7P6uRsNTkCJgSxG8gGhDW6rsP1qvbHmwSQqbV1S4dECy9Yq995B9gE2GbiES3RsBZurlKLogQI4FU6Y7O1DBcBMchv4jNIM0JdVgFR70QtpnzmyuA6wT+syCi10I3/sy98QXT0wvnjZrDUQj/aauAAF/hvGOmAPpTAUIKyBcI8IKAUXPohQigkKja0AVVFKYjc+htaGmXNgxSGzpuQ1M/Uu4TI7jNeMja4IRBtCadITWK3bpRDNuWbRPjvCt7jBzxrQapJnjtvic/RtZMGfmjRv0Q4cLkCv/yHPPETNmHWwqpyW2hA5D/QSKn7x14VgkVEZf/FtEA044inrZOte4+2ZYiEZZeRIIMITUO+hy8YwJkNxCLgXoLdoIKosEERgEARFUBpYHXWVMAAAAASUVORK5CYII=&quot;
                              style=&quot;height:16px;width:16px&quot; alt=&quot;&quot; data-csiid=&quot;45&quot; data-atf=&quot;1&quot;&gt;&lt;/div&gt;
                        &lt;/div&gt;
                      &lt;/div&gt;
                      &lt;div class=&quot;LbKnXb YAG2qc&quot;&gt;
                        &lt;div class=&quot;R8BTeb q8U8x OSrXXb&quot;&gt;Quora&lt;/div&gt;
                        &lt;div class=&quot;xuPcX yUTMj OSrXXb al4kQ&quot;&gt;5y&lt;/div&gt;
                      &lt;/div&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                &lt;/div&gt;
              &lt;/div&gt;
            &lt;/div&gt;
          &lt;/div&gt;
        &lt;/a&gt;&lt;/div&gt;
    &lt;/div&gt;
  &lt;/div&gt;
&lt;/div&gt;
</pre>
</details>

**Comment by iorate** [comment]
Please tell me the search words to reproduce this problem.

**Comment by Rapptz** [comment]
The one used for the screenshot should be "diarrhoea gummies" I think.

**Comment by iorate** [comment]
I reproduced the problem with search words `diarrhoea quora` and fixed it.

![discussions](https://github.com/iorate/ublacklist/assets/682043/acb0f1a6-8d2c-481d-9736-1569c49898fd)
