### ISSUE TITLE
The Blacklist was created in my download directory

### ISSUE THREAD

**Issue by CityguyUSA** [iorate/ublacklist#385]
I'd prefer the blacklist be somewhere in my LibreWolf profile rather than my download directory is it possible to move it?  What about syncing to the cloud?  Is it expected to be in the download directory?

**Comment by CityguyUSA** [comment]
It would be even better if it the blacklist could be shared across all browsers like %APPDATA%\uBlacklist\

**Comment by CityguyUSA** [comment]
Who's fault is that?

**Comment by iorate** [comment]
The blocklist file will not be created in your download directory unless you press the export button.
