### ISSUE TITLE
Can't restore settings from a file on Android

### ISSUE THREAD

**Issue by sn260591** [iorate/ublacklist#386]
The file browser won't let me select a settings file. It's possible that this is a firefox issue, but it doesn't occur with ublock origin (maybe because it uses the txt extension instead of json).

## Steps to Reproduce the Problem

1. Backup setting to file
2. Try to restore settings from this file

## Specifications

- Browser: Firefox 120
- OS: Android 8.0

**Comment by iorate** [comment]
I was able to select a settings file on my android device with android 10.
This issue may be device dependent.

**Comment by sn260591** [comment]
Well, can you add the ability to import/export the configuration as txt, please?
