### ISSUE TITLE
Use chrome.storage.sync instead of Google drive

### ISSUE THREAD

**Issue by verhovsky** [iorate/uBlacklist#39]
https://developer.chrome.com/extensions/storage

**Comment by iorate** [comment]
As written in that page, `chrome.storage.sync` has severe limitations, especially in size. The maximum size of one item is only 8,192 bytes. It is too small to store a blacklist for many users.

**Comment by verhovsky** [comment]
That makes sense why more extensions don't use it. Personally, my blocklist is 2KB (or 599 bytes gzip'd) and I'm too lazy to bother setting up a Google Drive, I don't mind recreating it from every new computer I log into chrome to. I would imagine most users of this extensions are the same, most probably haven't ever looked at the settings page. But I understand, managing such a small storage space in 8KB chunks and having an option to use Google Drive as well sounds like a lot of work.

**Comment by iorate** [comment]
Another reason why I don't use storage.sync is because it is not available in every Chromium- or Firefox- derivative.
I won't implement sync using storage.sync, but if you like, you can implement it as an option and create pull request.
