### ISSUE TITLE
Ublacklist doesn't work anymore on Kiwi on Android on Mobile View

### ISSUE THREAD

**Issue by cosminionita** [iorate/ublacklist#391]
When using the default mobile view, no sites are hidden, but when switching to Desktop, it works. Until a month ago, this was not the case and everything was working well.

- Browser: Kiwi Broswer for Android
- Other extensions/add-ons: I tried disabling all othe extensions and it didn't help.

- Search engine: Google
- Language: English

**Comment by iorate** [comment]
Chromium-based browsers for Android are not supported, although PRs are welcome.
https://github.com/iorate/ublacklist/issues/58#issuecomment-695652473
