### ISSUE TITLE
Support DuckDuckGo lite

### ISSUE THREAD

**Issue by jman-schief** [iorate/ublacklist#392]
hey, thanks for creating this WebExt!

By looking at the [DuckDuckGo patterns](https://github.com/iorate/ublacklist/blob/6d1cc6f640390d8511852a9e043210bf39383198/src/common/search-engines.ts#L277-L294) I wonder if the extension is supposed to already work on DuckDuckGo lite.

If not, I'd love if it could also support DuckDuckGo lite, its URL is `https://lite.duckduckgo.com/lite/`.

Would the extension blocking work also when DDG lite is used without javascript?

Thanks!

**Comment by iorate** [comment]
marked as todo

However, even if the lite version is supported, it will not work in Firefox due to content security policies. (Same reason why the html version is supported only in Chrome.)
