### ISSUE TITLE
Swiping back to search results page in iOS safari not working properly. 

### ISSUE THREAD

**Issue by DanielBurns** [iorate/ublacklist#398]
## Expected Behavior
Perform Google search. When tapping on search results and looking at new site I should be able to swipe back to search results to review other sites. This is how it works when I turn off the uBlacklist extension. 

## Actual Behavior
With the extension is active, whenever I swipe back to search results page, all that is presented is a plain white screen. I thought that’s all it was until I scrolled up once and saw that at the top was remnants of the page I was in before swiping back to search results. 

## Steps to Reproduce the Problem

1. Turn on uBlacklist extension 
2. Perform google search in iOS safari browser
3. Tap on a search result page. 
4. Swipe to go back to search results 

I can repeat this by turning off the extension and it works as normal. Turn the extension back on and the bug reappears. 

## Specifications

- Browser:
- Other extensions/add-ons: All turned off. 

- Search engine: Google 
- Language: English 
- Region: United States

**Comment by iorate** [comment]
I am also suffering from this problem. This problem occurs even when the extension is turned off, but less frequently than when it is turned on. In addition, the same problem occurs on some sites other than Google. The following is probably the same:
https://www.reddit.com/r/iOSBeta/comments/17woiy2/ios_172_db3_go_back_to_previous_page_in_safari/
I guess it is a bug of Safari 17.2. 

Turning off "Swap Processes on Cross-Site Navigation" in the Safari settings may suppress this problem.

ping @HoneyLuka

**Comment by HoneyLuka** [comment]
Sorry I can't reproduce this issue. My iOS version is 17.2.1. I'm unsure if this problem is specific to a particular website. Please give me a search word and the search result item you clicked on, and I will try again.

**Comment by iorate** [comment]
@HoneyLuka Sorry for my late reply. This problem occurs regardless of the search term.

Because the same problem occurs in some sites that are not search engines, I guess it is mainly due to a bug of Safari, but it occurs more frequently in Google with this extension enabled.

**Comment by iorate** [comment]
I believe this problem is completely resolved in v8.8.3 for Safari.
Please request reopen if the problem persists.
