### ISSUE TITLE
Must be something simple... /redirects/ isn't working

### ISSUE THREAD

**Issue by realAzazello** [iorate/ublacklist#408]
## Expected Behavior
I must be missing something so simple in the regex.

I'ld like to block results with `/redirects/` in the path e.g. :

https://docs.example.com/routing/redirects/

Anywhere in the path, middle or end.

As test, have only these rules:

```
title/Redirecting/
# /redirects/
*://*/redirects/*
```

## Actual Behavior
Doing a gsearch: https://www.google.com/search?q=%22redirects%22

Still shows results.

## Steps to Reproduce the Problem

1. **Disabled** uBl**[o](https://github.com/gorhill/uBlock)**ck
2. **Disabled** Tampermonkey - no userscripts running
3. Too many extensions to disable. (If needed later, I'll try on a fresh install)
4. Tried using solution from https://github.com/iorate/ublacklist/issues/101#issuecomment-884741826: `*://*/redirects/*` -- doesn't work in my setup
5. Tried `/redirects/` -- never worked, even with earlier Firefox versions

## Specifications

- Browser: Firefox 115.6.0esr
- uBlacklist version: 8.5.0
- Other extensions/add-ons: Too many to list

- Search engine: Google
- Language: English
- Region: US

**Comment by iorate** [comment]
`/redirects/` (or `/\/redirects\//`) should work.

Make sure that the URL you are trying to block really contains `redirects` (not `redirect` or `Redirects`).

**Comment by realAzazello** [comment]
I wish you hadn't closed this before getting my feedback.


> Make sure that the URL you are trying to block really contains redirects (not redirect or Redirects).

I already wrote that I confirmed that:
>     Doing a gsearch: https://www.google.com/search?q=%22redirects%22
>     
>     5. Tried `/redirects/` -- never worked, even with earlier Firefox versions
In fact `/redirects/` is what triggered my investigation--months ago--as I knew it never worked on my setup.

Eureka! `/\/redirects\//` works...
![image](https://github.com/iorate/ublacklist/assets/86322218/90c830c1-1c87-441f-9830-bd74d28cb2ec)

But also triggers on
```
https://experienceleague.adobe.com/docs/analytics/technotes/redirects.html?lang=en
https://www.searchenginejournal.com/redirects-beginner-guide/436231/
https://bluehost-cdn.com/hosting/help/redirects
https://www.geoedge.com/auto-redirects/
```

I'll live with it, but I wish to have the exact `/redirects/`, hard-match on both `/`
