### ISSUE TITLE
[Frefox] incorrect compatibility

### ISSUE THREAD

**Issue by quroe** [iorate/uBlacklist#41]
uBlacklist shows `Works with firefox 48.0 and later, android 48.0 and later` in AMO.
But uBlacklist(3.1.0 and later) uses Element.attachShadow(), so it works with fx63(59) and later.
https://developer.mozilla.org/ja/docs/Web/API/Element/attachShadow

I'm using Firefox fork like Waterfox Classic, Serpent(Basilisk).
If you fix and work with fx48, I'm very happy.
But I don't strongly desire it because it is labor intensive.
Thanks.

**Comment by iorate** [comment]
Sorry, I have no motivation to support Firefox version < 63 (and equivalent Firefox forks).

You can still block websites by manually editing the list in the options page, so I won't change the minimum required version to 63.

**Comment by iorate** [comment]
As for Waterfox Classic, uBlacklist seems to work with version 2020.06 with `dom.webcomponents.enabled` `true`.

**Comment by quroe** [comment]
Sorry for the delay in responding.

> You can still block websites by manually editing the list in the options page, so I won't change the minimum required version to 63.

I hadn't thought of that method, thank you.
Waterfox has just supported `Partial Shadow DOM v1 support (experimental)` from 2020.06!
Thanks a lot.
