### ISSUE TITLE
Regular Expressions Not Working

### ISSUE THREAD

**Issue by afrazkhan** [iorate/uBlacklist#42]
## Expected Behavior
Something like `.*pinterest.*` should block any URL containing the string "pinterest" (this example is aggressively greedy for the sake of simplicity).

## Actual Behavior
Doesn't ;)

## Specifications

  - OS: MacOS
  - Browser: Firefox 76
  - Other extensions that might interfere: None that I know of

**Comment by iorate** [comment]
uBlacklist requires regular expression *literals* in JavaScript. `/.*pinterest.*/` (surrounded by `/`) will work. (In this case, `/pinterest/` is more efficient)

**Comment by afrazkhan** [comment]
Yup, my bad. Adding the surrounding `/` works perfectly.
