### ISSUE TITLE
Support banning a site only from image search

### ISSUE THREAD

**Issue by nonetrix** [iorate/ublacklist#422]
Annoyingly, there is a ton of CEO spam on image searches, mainly from Redbubble and other shopping sites that makes finding a original image for a meme almost impossible these days. I also have a feeling that Google prioritizes them to get you to buy crap. But even worse, it has affected more reputable brands like eBay and Amazon. So banning Amazon would be too extreme, but I would like to ban them from image searches since in my opinion it is completely irrelevant when I am looking for a image 99% of the time.

Issue with Amazon:
![image](https://github.com/iorate/ublacklist/assets/45698918/2033f957-9848-4686-b304-88f66c1320ff)

Issue as a whole without banning any sites from search:
![image](https://github.com/iorate/ublacklist/assets/45698918/f7f343ee-eae3-40d4-b020-ee29d118a03e)

As you can see half of them are just tshirts, cups, mugs, prints, prints that are cropped, and sites that don't even own the copyright likely adding watermarks to try to scam you into buying it, and everything but what I actually want which is the original image

**Comment by nonetrix** [comment]
This is important to me

**Comment by iorate** [comment]
v8.8 or later supports this feature.
```
*://*.amazon.com/* @if($category="images")
```
