### ISSUE TITLE
Blocked sites not blocked in new Google "bubble" layout

### ISSUE THREAD

**Issue by squabbled** [iorate/ublacklist#427]
## Expected Behavior
On the new Google layout, when searching for someone like "Elon Musk" sometimes shows info cards with birthdates, images, and social network updates (Twitter, Facebook, Instagram, etc). These should be blocked
## Actual Behavior
The info cards are still present with a link to the site, I have both x.com and twitter.com blacklisted (for mental health reasons) and when searching "Elon Musk" the regular result for his Twitter page is removed, the info card with his latest tweet is still present.
## Steps to Reproduce the Problem

1. Blacklist a site like Facebook, Twitter, Instagram
2. Search on Google (new layout only) for a celebrity
Github's not playing nice with Flameshot screenshots so I just uploaded it elsewhere -  https://www.katsudon.cc/images/2024-03-15_19-26.png

## Specifications

- Browser: Mozilla Firefox on Pop OS
- Other extensions/add-ons: uBlock Origin (with AI Google blacklist), stylus, tampermonkey, translator, downthemall, search by image, indie wiki buddy, and heaps others

- Search engine: Google
- Language: English
- Region: United States

**Comment by aug-dev** [comment]
Hey, thanks for the suggestion!

There is currently a PR #454  waiting for review that begins to implement this feature.
