### ISSUE TITLE
[feature request] link to settings page in popup

### ISSUE THREAD

**Issue by verhovsky** [iorate/uBlacklist#43]
Right now if I want to see or edit all the urls I've blacklisted I have to click the triple dot > Extensions > uBlacklist > Details > scroll down > Extension options. It would be convenient if I just had to click on the popup > "See all blocked sites". Like I can with uBlock Origin.

**Comment by iorate** [comment]
In Chrome, you can right-click the toolbar icon and select "Options" (two clicks).
