### ISSUE TITLE
Cannot add BBC to block list

### ISSUE THREAD

**Issue by pjmattingly** [iorate/ublacklist#431]
## Expected Behavior

Expected to add BBC to the block list. The regex appears in the block list, but then is removed on the addition of any other item.

## Actual Behavior

The regex for the BBC appears in the block list, but then is removed on the addition of any other item.

## Steps to Reproduce the Problem

1. Click the "Block this site" button associated with `bbc.com`.
2. Observe the regex for the BBC in the "Sites blocked from appearing in Google search results" list; `*://*.bbc.com/*`.
3. Click the "Block this site" button associated with any other site.
4. Refresh the "Sites blocked from appearing in Google search results" and observe that the `*://*.bbc.com/*` has been removed, while the regex for the site added in step 3 is present.

## Specifications

- Browser: Firefox.
- Other extensions/add-ons: 
![image](https://github.com/iorate/ublacklist/assets/6288999/076b1a6d-d974-4069-aae4-a1064859fd59)

- Search engine: NA
- Language: NA
- Region: NA

----

Possible workaround. Manually adding the regex associated with blocking the BBC appears to resolve the issue. More specifically, adding the regex `*://*.bbc.com/*` to the "Sites blocked from appearing in Google search results", saving the list, and then attempting to use the "Block this site" button on another site does not remove the `*://*.bbc.com/*` regex from the "Sites blocked from appearing in Google search results" list; Then also the regex used for the "other site" also appears in the list normally.

**Comment by aug-dev** [comment]
Hey there!

I tried to reproduce the issue on a clean install of Firefox and it didn't occur as stated.

![image](https://github.com/iorate/ublacklist/assets/109992671/88fe46c2-a676-4095-ae62-2694913ccd35)

I find it unlikely to be related to the other extensions... But it's worth a check!

Could you please check if the problem also occurs if the other extensions are disabled?

I'll try again tomorrow on a different version of Firefox and on Chromium to see if I get the issue.
