### ISSUE TITLE
It doesn't work on Google image search in Safari on iOS.

### ISSUE THREAD

**Issue by 0rodna1** [iorate/ublacklist#435]
## Expected Behavior
Block sites.
"Block this site" links appear.
The number of blocked sites and the "Show" link appear.

## Actual Behavior
Doesn't block.
Don't appear.
Don't appear.

## Steps to Reproduce the Problem

1. Search for images on Google.

## Specifications

- Browser: Safari iOS 15.8.2 uBlacklist Version 8.5.1
- Other extensions/add-ons: AdGuard Pro Version 4.5.2 (recommended filters only)

- Search engine: Google
- Language: Japanese
- Region: Japan

**Comment by iorate** [comment]
probably same as #476 and fixed by #485

**Comment by 0rodna1** [comment]
It started to work with images safely. Thank you.

But, this time, it no longer works with videos/movies.

Browser: Safari iOS 15.8.3 uBlacklist Version 8.9.2
Other extensions/add-ons: AdGuard Pro Version 4.5.5 (recommended filters only)
