### ISSUE TITLE
Blocked sites still appear in Google's "Questions & answers" section

### ISSUE THREAD

**Issue by zachpoblete** [iorate/ublacklist#437]
## Expected Behavior
Blocked sites should be blocked everywhere; I shouldn't see them in Google's "Questions & answers" section.

## Actual Behavior
Blocked sites still appear in Google's "Questions & answers" section.

## Steps to Reproduce the Problem

1. Block a site that usually appears in Google's "Questions & answers" section (Quora in the example below)
1. Find that it's blocked in normal search results but not blocked in the "Questions & answers" section

![Screenshot 2024-03-29 122059](https://github.com/iorate/ublacklist/assets/92368853/fd66ff75-b2b1-4013-bc4a-eb7561707272)

## Specifications

- Browser: Microsoft Edge
- Other extensions/add-ons:

- Search engine: Google
- Language: English
- Region: Philippines

**Comment by aug-dev** [comment]
No problem! :)
