### ISSUE TITLE
Recently, Google Image Search has not been functioning properly for the past few days

### ISSUE THREAD

**Issue by burosi** [iorate/ublacklist#440]
## Expected Behavior

Recently, Google Image Search has not been functioning properly for the past few days

## Actual Behavior 

The blocking feature on the right-hand side tab in the image search results is not working.

## Steps to Reproduce the Problem

1. The functionality on the main page of the image search results is working properly.

2. However, it's not working on the right-hand side tab.
![2](https://github.com/iorate/ublacklist/assets/166276743/00ca40a5-a6ec-4005-8177-294fdfd93e20)

## Specifications

- Browser: google chrome
- Other extensions/add-ons: adguard

- Search engine: google
- Language: english, japanese
- Region: japan

**Comment by iorate** [comment]
not reproducible in my environment at the moment

**Comment by iorate** [comment]
fixed by #523
