### ISSUE TITLE
'title/' blocking is not occuring on the exact word being filtered

### ISSUE THREAD

**Issue by realAzazello** [iorate/ublacklist#441]
Might be related/exact to https://github.com/iorate/ublacklist/issues/421

## Expected Behavior
Using expression `title/anal/i`. Expect **only** case-INsensitive "anal" word to be filtered in results' titles.

## Actual Behavior
Titles with words like 'Analytics' and 'Analyst' are being blocked.

## Steps to Reproduce the Problem

1. Use filter `title/anal/i`
2. Do a Gsearch on `("salary" | "pay range") "Compliance Manager"`

## Specifications

- Browser: Firefox 115.6.0esr
- Other extensions/add-ons: _Disabled Tampermonkey_

- Search engine: Google
- Language: English
- Region: US

**Comment by iorate** [comment]
`title/\banal\b/i`
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Word_boundary_assertion
