### ISSUE TITLE
[Enhancement] ability to customize "Block this site" link string

### ISSUE THREAD

**Issue by Polisson** [iorate/ublacklist#447]
My concept is simple - user may need to replace the name of functionality and call it other than  "Block this site". 
It would be especially useful if Unicode characters supported, so the string would be even like an icon 🛇
Also, searching in multiple languages, the default string ruins the aesthetics or makes it difficult to read like on Brave search (puzzle: find "Block this site" in such image):

<img src="https://github.com/iorate/ublacklist/assets/24476033/a80e1ef3-ee13-45fc-ae1b-48841124a6ff" width=50% height=50%>

Ofc _"Unblock string"_ has to have the same feature.

**Comment by iorate** [comment]
Customization of the string is not planned.

Instead, I have a plan to replace the “Block this site” links with *overlay* icons on search result entries, as keeping “Block this site” links at proper positions requires significant maintenance costs, although details are yet to be determined.
