### ISSUE TITLE
Not working at all on Startpage with version 8.6.0

### ISSUE THREAD

**Issue by linlinxza** [iorate/ublacklist#453]
## Expected Behavior

Filtering should work on startpage.

## Actual Behavior

Not filtering at all.

## Steps to Reproduce the Problem

1. Install addon
2. Add an expression like *://*.reddit.com/*
3. Enable for startpage.com
4. Activate
5. Search for reddit

## Specifications

-     Browser: Librewolf
-     Search engine: Startpage.com
-     Language: EN
-     Region: CA

Again, it might be worth also checking the mobile version of startpage.

**Comment by GoldenMariaNova** [comment]
It's even worse. The extension can't even access its own options.

This "update" broke the _entire_ extension.

**Comment by linlinxza** [comment]
I can access it's options interestingly enough. But yeah. This addon needs to be fixed. I don't know of any other method to filter out the crap online (like the Lizard's Meta crap).

**Comment by jedomed** [comment]
I'm also using Librewolf, filtering works on Google and DDG but on Startpage

**Comment by linlinxza** [comment]
> I'm also using Librewolf, filtering works on Google and DDG but on Startpage

Yeah. I'm also aware of that.

**Comment by linlinxza** [comment]
This is strange. If I install it and allow it to work on private windows, the addon will work briefly on startpage. But after that, it won't.

**Comment by jedomed** [comment]
If you have uBlock, adding `startpage.*##.result:has(a[href*="*.fandom.com"])` to your filters seems to do the job. Just wanted to mention it as an alternative, 'cause I kept accidentally clicking on sites I had blacklisted ever since the extension broke.

**Comment by linlinxza** [comment]
> If you have uBlock, adding `startpage.*##.result:has(a[href*="*.reddit.com"])` to your filters seems to do the job. Just wanted to mention it as an alternative, 'cause I kept accidentally clicking on sites I had blacklisted ever since the extension broke.

Thank you! I'll do that. I'm already making custom lists on Github for my repos to try and block all the stuff I see as trash online.

**Comment by jedomed** [comment]
Correction: `startpage.*##.result:has(a[href*="www.reddit.com"])`
my original example works for blocking Fandom (`startpage.*##.result:has(a[href*="*.fandom.com"])`) but not Reddit, not sure why, anyway as I'm typing this uBlocklist started magically working again haha. I think it heard that I was about to replace it with uBlock.

**Comment by linlinxza** [comment]
I went with this:

`startpage.*##a[href*=".reddit."]:upward(1)`

That works. And I ironically, I got it from Reddit. It was for Google searches. But it seems to work on startpage as well.

**Comment by linlinxza** [comment]
Now I got my list for search results working. If I can get the same effect for image results, then it would be perfect.

**Comment by iorate** [comment]
This issue was opened before v8.6.0 was published on AMO (May 13) :confused:

It was intentional that Startpage image search was left unsupported: #243. (The situation is different now and pull requests are welcome)

**Comment by linlinxza** [comment]
> This issue was opened before v8.6.0 was published on AMO (May 13) 😕
> 
> It was intentional that Startpage image search was left unsupported: #243. (The situation is different now and pull requests are welcome)

Don't need this extension now. I made my own Ublock filters of domains I despise; and it's a long list. Example of that list:

Desktop:
`startpage.*##a[href*="facebook"]:upward(1)`

Mobile (on a separate list):
`startpage.*##a[href*="facebook"]:upward(2)`

Images (desktop and mobile):
`startpage.*##.image-container:has(div.image-quick-details span:has-text(facebook))`

I'm good.
