### ISSUE TITLE
Completely unable to work at all (Inability to even access the options)

### ISSUE THREAD

**Issue by GoldenMariaNova** [iorate/ublacklist#455]
## Expected Behavior
To be able to change settings and sync.

## Actual Behavior
You can't even access the options.

## Steps to Reproduce the Problem
1. Just go to the extension options in Chrome (Ex: **Brave**), the problem is immediate.

**Comment by aug-dev** [comment]
Hey!

What was your method of installing the extension? (Did you install it through the Chrome web store, or did you download the file directly?

I'm asking this, because I had some trouble with the manifest v2 version of the extension running on Brave as well.

**Comment by GoldenMariaNova** [comment]
> snips

Literally from Google Chrome store. I'm also on **Brave**.

**Comment by aug-dev** [comment]
I tested on Brave, Firefox, and Chromium and still, I was not able to reproduce this issue.

Could you tell your browser version and or the extension's version?

Any additional information would be useful.

**Comment by BiggerMini** [comment]
I'm running into this issue as well。
my firefox version is 127.0
add-on version is 8.7.1

**Comment by iorate** [comment]
No additional information was provided for over a month.
Given that other users have not reported the same problem, I believe that this "bug" is highly dependent on the environment of the person who opened this issue.
