### ISSUE TITLE
Discussions and Forums not filtered, again

### ISSUE THREAD

**Issue by Ataraxia-Mechanica** [iorate/ublacklist#457]
## Expected Behavior
Discussions and Forums filtered

## Actual Behavior
![image](https://github.com/iorate/ublacklist/assets/111327195/480355d2-6331-480e-a689-a14ea994a2f3)
![image](https://github.com/iorate/ublacklist/assets/111327195/25e99d48-04cb-4e24-aa3a-2d287d289205)
![image](https://github.com/iorate/ublacklist/assets/111327195/50a59ca4-1218-4a07-a425-90293a743f2f)
No filtering, same as #376

## Steps to Reproduce the Problem

1. Search "social media detox"

## Specifications

- Browser: Firefox w/ uBlacklist Version: 8.5.1
- Other extensions/add-ons:

- Search engine: Google
- Language: EN
- Region: US

**Comment by aug-dev** [comment]
I will look into it.

**Comment by aug-dev** [comment]
Here it is: #458

^^

**Comment by iorate** [comment]
@aug-dev Thank you for fixing this issue.
