### ISSUE TITLE
Remove "Google" from repo description and README

### ISSUE THREAD

**Issue by rpdelaney** [iorate/ublacklist#460]
The repository description + the README are such that every time I send a link to this repo to a privacy-conscious friend they say "I don't use Google." But this browser add-on supports more search engines besides just Google, so you should say "search engines" instead.

**Comment by aug-dev** [comment]
Hey there!

This is already an ongoing discussion, see: #405.

**Comment by rpdelaney** [comment]
Thanks! This is a duplicate then, closing
