### ISSUE TITLE
Feature request: override more general with more specific ones

### ISSUE THREAD

**Issue by pjmattingly** [iorate/ublacklist#461]
For example, I've set ublacklist to block the `ai` domain; Since it seems to be full of scammy sites.

But, every once in a while I find sites in the `ai` domain that I'd like to see in searches; One of these is `opencv.ai`.

And so, if I enter the following patterns, then `opencv.ai` remains blocked, though I have setup a rule allowing it be shown and color-coded:

```
*://*.ai/*
@1*://opencv.ai/*
```

And so, it would be great if I could override the first rule with the second; Or mark the second rule to override the more general rule.

**Comment by iorate** [comment]
Highlight rules *always* override block rules.

The reason why your second rule does not highlight OpenCV.ai is because the host name of OpenCV.ai is `www.opencv.ai`, not `opencv.ai`. The following rules will work:
```
*://*.ai/*
@1*://*.opencv.ai/*
```
