### ISSUE TITLE
The "blocked {n} sites" string overlaps with the "Tools" menu on Google

### ISSUE THREAD

**Issue by pjmattingly** [iorate/ublacklist#463]
## Expected Behavior

I would expect the "uBlacklist has blocked {n} sites" string to not overlap items on Google search pages.

## Actual Behavior

I was attempting to do an advanced search through Google. When clicking their "Tools" button, the menu appeared showing: 

![image](https://github.com/iorate/ublacklist/assets/6288999/01b9348b-572e-4930-ae3d-f218ba9b4dfa)

Note that the "Any Time", "All results", and "Advanced Search" buttons are overlapped with the "uBlacklist has blocked {n} sites" string.

## Steps to Reproduce the Problem

1. Add a site to uBlacklist which will be blocked in a search on Google.
2. Conduct that search on Google; Noting the "uBlacklist has blocked {n} sites" string that appears below the search bar.
3. Click the "Tools" button next to the Google search bar.
4. Observe the overlap between the "uBlacklist has blocked {n} sites" string and the buttons associated with the "Tools" button from Google search.

## Specifications

- Browser: Firefox 125.0.3 (64-bit)
- Other extensions/add-ons: None (disabled all other addons to test)

- Search engine: Google
- Language: English
- Region: AMER

Note, a possible solution may be to move the "uBlacklist has blocked {n} sites" string to location 1 or 2, as these locations appear to be unused:

![image](https://github.com/iorate/ublacklist/assets/6288999/8d18d72d-03c0-40bf-9084-a1ba76650474)

**Comment by aug-dev** [comment]
I was able to reproduce this issue.

![image](https://github.com/iorate/ublacklist/assets/109992671/0a76b4dd-c724-4c93-ab04-32544a54f9e2)

I'll look into it.

**Comment by aug-dev** [comment]
Here's the PR that fixes this issue: #478.

:P
