### ISSUE TITLE
[FYI] Using 'udm=14' hides/blocks "Block this site" option on Gsearch results

### ISSUE THREAD

**Issue by realAzazello** [iorate/ublacklist#465]
Not a problem report {maybe}, more just for headsup...

Note that `udm=14` refers to ["_a new Google Search 'Web' filter that shows only text-based links_"](https://tech.slashdot.org/story/24/05/16/1410259/revolutionary-new-google-feature-hidden-under-more-tab-shows-links-to-web-pages) that can also be triggered by adding the parameter to GS urls: https://tech.slashdot.org/comments.pl?sid=23325119&cid=64477411

## Expected Behavior
To see uBlacklist's "**Block this site**" option on 'Google Search' results

## Actual Behavior
If `udm=14` is added to Gsearch url, "**Block this site**" is hidden/removed on results

## Steps to Reproduce the Problem

1. Disable uBlock, Tampermonkey
2. Compare... https://www.google.com/search?q=%22udm%3D14%22+%22google+search%22
3. to... https://www.google.com/search?q=%22udm%3D14%22+%22google+search%22&udm=14

## Specifications

- Browser: Firefox 115.6.0esr
- Other extensions/add-ons: uBlock, Tampermonkey

**Comment by trumad** [comment]
I've switched to udm=14 as my main search engine now, from Kagi. Having the ability to hide results would be nice to have.

**Comment by aug-dev** [comment]
I'll look into this.

**Comment by aug-dev** [comment]
Fixed by  #474.

Thanks for the bug report, this one was really interesting.
