### ISSUE TITLE
Feature request: add more search engines

### ISSUE THREAD

**Issue by GrayedFox** [iorate/uBlacklist#47]
I haven't looked into your code friend so I don't know if this would be trivial or not, but would intercepting and removing search results from DuckDuckGo, for example, be as simple as adding this line `https://duckduckgo.com/?q=` to the end of the [google-matches.js](https://github.com/iorate/uBlacklist/blob/master/src/google-matches.js) file?

**Comment by GrayedFox** [comment]
Of course, giving the user the option to decide which search engines to filter might be slightly more "user friendly", but I for one would be happy if uBlacklist removed search results from any/all search engines by default. Haven't used Google in a while and likely won't, but it would be a shame to let go of uBlacklist, been using it for many years now :)

**Comment by iorate** [comment]
In #19, I wrote:

> If a new version of Chrome extension requires an additional permission, Chrome will disable extensions of existing users until they manually re-enable their extensions.
This is a proper behavior for security reasons, but not acceptable to this extension, with a certain number of existing users.
New permissions should not be required by default.

Adding a search engine filtered by default will temporarily disable all existing users' installation. I don't want to do it.
This situation may be changed by Manifest V3, but it has not come yet.

**Comment by GrayedFox** [comment]
Fair enough. Since I'm never really using Google to search for anything any more, uBlacklist is unfortunately not doing much for me - thanks for the good times however :+1: :bow:

**Comment by iorate** [comment]
As for DDG, there is an option to use it (requires restart on Firefox, it's a bug)

![ddg1 0](https://user-images.githubusercontent.com/682043/86917297-d05c8680-c15f-11ea-8012-8ae39c5a9e57.png)

![ddg2 0](https://user-images.githubusercontent.com/682043/86917307-d488a400-c15f-11ea-8690-d8265c858810.png)

**Comment by GrayedFox** [comment]
In all my years of using uBlacklist I never **once** saw that preferences page!!! Word to the wise: maybe consider adding a "preferences" button to the left of the cancel button inside the browser popup? 

Hhaving to `right click the uBlacklist icon > Manage Extension > Ellipses Button > Preferences` is a huge pain in the ass (and very hidden from the user!). Thanks for the update.

**Comment by iorate** [comment]
reopen #43
