### ISSUE TITLE
Traditional Chinese is not displayed

### ISSUE THREAD

**Issue by bennylee1029** [iorate/ublacklist#472]
## Expected Behavior
With localized Traditional Chinese translation displayed on search engine and extension settings.
## Actual Behavior
Only displayed in English.
## Steps to Reproduce the Problem

Uninstall and reinstall the extension didn't help.
Cookies have been cleared.

## Specifications

- Browser: Edge/Safari
- Version: 8.6.0/8.6.2

**Comment by Tback1** [comment]
zh-cn also
