### ISSUE TITLE
[{?} sites blocked by uBlacklist] [Show] is not displayed.

### ISSUE THREAD

**Issue by miso-nikomi-nasu** [iorate/ublacklist#475]
## Expected Behavior
Is displayed.
## Actual Behavior
Do not show.
## Steps to Reproduce the Problem

1. Search on Google using [Video search], [Image search], [Shopping], and [News].
2.{n} sites blocked by uBlacklist] [Show] is not displayed.

## Specifications

Browser:Chrome
Other extensions/add-ons:

Search engine:Google search
Language:Japan
Region:Japan

**Comment by miso-nikomi-nasu** [comment]
We have also prepared images
![The Parade of the Wooden Soldiers](https://github.com/iorate/ublacklist/assets/54824743/7eefe9c0-f0c4-4864-9bee-01d3babc7ef2)

**Comment by aug-dev** [comment]
I'm going to look into it.

**Comment by aug-dev** [comment]
These PRs pretty much solve the problem.

By the way, the "Shopping" section is currently not supported by uBlacklist, so that is kind of not a bug.   😅
