### ISSUE TITLE
Add Web Search (vanilla google search) to default google url lists?

### ISSUE THREAD

**Issue by ctyler9** [iorate/ublacklist#477]
https://www.google.com/search?q=%s&udm=14

I have a custom google search URL that includes this to avoid clutter/AI junk. would be nice to add this to default list in search-engines.ts? Wildcard search?q* doesn't seem to work?

**Comment by aug-dev** [comment]
Hey there!

This is a duplicate of #465, and the issue has been solved already in the new version of uBlacklist released today (8.7.0).

It'll soon be on Chrome/Firefox store. :P

**Comment by ctyler9** [comment]
damn that was quick! thanks
