### ISSUE TITLE
Opera Browser

### ISSUE THREAD

**Issue by pablo-hp** [iorate/ublacklist#481]
Opera browser.

For some reason, the extension does not work correctly in the Opera browser.
I know the extension only exists in the Chrome store, but I would like to be able to use the extension in the Opera browser.

**Comment by aug-dev** [comment]
![image](https://github.com/iorate/ublacklist/assets/109992671/9ea9badf-05c6-4c4f-bbde-f628e6935484)

Pô, ai não Pablo, na moral KKKKK

**Comment by aug-dev** [comment]
Jokes aside, thanks for reporting this, I may look into it in the future.

**Comment by pablo-hp** [comment]
Lol, kkkk

Foi mal, corrigi a avaliação lá.
5 estrelas.

Parabéns pelo atendimento.
________________________________
De: Pedro Augusto ***@***.***>
Enviado: sexta-feira, 31 de maio de 2024 18:49
Para: iorate/ublacklist ***@***.***>
Cc: Pablo Hernandez ***@***.***>; State change ***@***.***>
Assunto: Re: [iorate/ublacklist] Opera Browser (Issue #481)


image.png (view on web)<https://github.com/iorate/ublacklist/assets/109992671/9ea9badf-05c6-4c4f-bbde-f628e6935484>

Pô, ai não Pablo, na moral KKKKK

**Comment by Rajdave69** [comment]
Translation of the option you have to check: `Allow access to search page results`
![{E2041495-5577-46A8-A615-54E885C9BCA1}](https://github.com/user-attachments/assets/78b2632e-ece1-4373-87d5-4e9418e2e37b)
