### ISSUE TITLE
[Safari]"Block this site" button in google search list display issue

### ISSUE THREAD

**Issue by HoneyLuka** [iorate/ublacklist#493]
This seems to be a problem that only exists in Safari.

![Screenshot 2024-06-18 at 15 50 09](https://github.com/iorate/ublacklist/assets/4635725/df174b45-0d65-44d4-a061-013e990f99b7)

I found it can be fixed by adding a ```z-index: 1``` on the "Block this site" button's parent element

![Screenshot 2024-06-18 at 15 51 55](https://github.com/iorate/ublacklist/assets/4635725/2378a9d3-0787-420b-aa4e-4d9d718aa20c)

![Screenshot 2024-06-18 at 15 51 17](https://github.com/iorate/ublacklist/assets/4635725/d38698c3-2ebf-4987-88da-a0112e886ff7)

**Comment by iorate** [comment]
@HoneyLuka Sorry for my late response.

I think this is a bug in Safari or Google, since the "translate this page" links do not appear even with this extension turned off.
I wonder if this extension is responsible for fixing this problem.
Anyway, could you please try #507?
