### ISSUE TITLE
v8.8.1 Stopped working on Firefox (127.0.1 Windows 11) as of June 22, 2024

### ISSUE THREAD

**Issue by DUser6** [iorate/ublacklist#497]
Personal Blocklist has been wiped and Importing & saving doesn't work anymore
(Reddit & Know Your Meme are supposed to be blocked)
![Screenshot 2024-06-22 at 10-46-55 asdf at DuckDuckGo](https://github.com/iorate/ublacklist/assets/98536563/3a633bd7-a63e-436f-8fbd-9873b5c54d6d)
![Screenshot 2024-06-22 at 10-47-24 asdf - Google Search](https://github.com/iorate/ublacklist/assets/98536563/55108aec-c528-4528-bbe3-fddbf9a43366)

The blocklist is always reset, and doesn't update in private windows even if Firefox grants permission
![Screenshot 2024-06-22 at 10-51-43 Add-ons Manager](https://github.com/iorate/ublacklist/assets/98536563/f1c4e6e5-419d-48ae-8931-aecbd00758e0)

"Other search engines" & "Add rules blocking whole sites by default" doesn't work either. It only works if I add each website one at a time. Even then, Google is either slow to load or doesn't load at all.
![Screenshot 2024-06-22 at 10-56-52 ](https://github.com/iorate/ublacklist/assets/98536563/25937ed6-0e76-4dc6-b306-9e3667f3d3ac)
![Screenshot 2024-06-22 at 10-57-10 ](https://github.com/iorate/ublacklist/assets/98536563/8006f5ea-81b8-40fc-b3f9-0682e5b8fc9b)

[uBlacklist.txt](https://github.com/user-attachments/files/15937219/uBlacklist.txt)
Turning off other add-ons didn't work.
It also didn't work in the recent version of Brave

**Comment by iorate** [comment]
Thank you for attaching your ruleset. The problem you encountered is at least partly due to invalid rules such as:

```
*://*giantfreakinrobot.com
*://*givemesport.com/*
*://*gizmodo.com/*

# Right:
*://*.giantfreakinrobot.com/*
*://*.givemesport.com/*
*://*.gizmodo.com/*
```
