### ISSUE TITLE
[Bug] DuckDuckGo's "More Videos" button overlaps search results when using uBlacklist

### ISSUE THREAD

**Issue by Uneccessary** [iorate/ublacklist#502]
## Expected Behavior

The "More Videos" button behaves just like when using DDG without uBlacklist

## Actual Behavior

The "More Videos" button overlaps the result beyond it

## Steps to Reproduce the Problem

1. Enable uBlacklist for DuckDuckGo
2. Search for something which causes video results to appear
3. The more videos button will overlaps the result beyond it.

## Specifications

- Browser: Brave Browser
- Other extensions/add-ons:
None.

- Search engine: DuckDuckGo
- Language: --
- Region: --

**Comment by aug-dev** [comment]
Could you please send a screenshot of the problem?

That would help a lot.

**Comment by Uneccessary** [comment]
![duckduckgo-github-is-stupid](https://github.com/iorate/ublacklist/assets/145043411/8e2b6365-7336-47bc-9414-43f4f84e5d9a)

Search query: tmux intro

**Comment by Uneccessary** [comment]
![duckduckgo-github-is-stupid](https://github.com/iorate/ublacklist/assets/145043411/72b27f3c-076c-4d6b-8782-6c2237cee4ff)

Search query: Tmux intro

**Comment by aug-dev** [comment]
Thanks for your screenshot.

I haven't been able to reproduce this issue.

I tested on Chromium, Brave and Firefox. Changing DuckDuckGo's language and region settings didn't work either.

![Screenshot from 2024-07-19 21-02-15](https://github.com/user-attachments/assets/30a4e1da-e924-4196-81e0-8140345ddf18)

Are you still facing this issue? If so, can you think of any additional information that could help me reproduce it?

This *might* be a regional thing.

**Comment by Uneccessary** [comment]
Hm, that's awkward. I tried disabling Brave Shields and uBO, since it could be related to some filterlist or personal tweaks I've made, but no, the button still stays the same.

My region is: Germany

**Comment by Uneccessary** [comment]
I figured it what causes the issue, if you change the background color of DuckDuckGo within DuckDuckGo's Search engine settings it causes the "More Videos" button to overlap the results when using it with uBlacklist

**Comment by aug-dev** [comment]
![image](https://github.com/user-attachments/assets/5b1b8f06-2912-46b6-9e2d-6dd1634adc4d)

Cool, I was able to reproduce it.

Very weird bug.

I'll see what I can do.

**Comment by iorate** [comment]
fixed in #514 (thanks to @aug-dev)
