### ISSUE TITLE
Don't ask for permissions immediately after installation

### ISSUE THREAD

**Issue by ghost** [iorate/uBlacklist#52]
I use DuckDuckGo, but not Google.
And yet, you are forced to ask for Google permissions.
Like DuckDuckGo and Startpage, I'd like to see the system allow it manually.

**Comment by iorate** [comment]
I think it reasonable to require Google permissions on install, because most users use Google and are not familiar with permissions.

**Comment by gif-byte** [comment]
Do not invade the privacy of the minority. :(

**Comment by gif-byte** [comment]
I think it's important to remain neutral in creating software, not favoring any particular service.
Firefox's default search engine is Google. But it can be removed or changed.
Such neutrality is now required of uBlacklist.
