### ISSUE TITLE
Google images 'related images' not being filtered

### ISSUE THREAD

**Issue by joospotter** [iorate/ublacklist#521]
When using google images, while the filter works for the images themselves, the 'similar / related images' sidebar that pops up when clicking any given image will not be filtered.

**Comment by aug-dev** [comment]
Hey there!

What browser are you using? Is the problem showing up on Desktop or on the mobile version?

A screenshot and an example search query to reproduce the issue would **really** help.

**Comment by joospotter** [comment]
Hi,

I'm using Firefox - it's the Desktop version. 

You can see the 'blacklist has blocked 46 sites' message in the screenshot, but the two I have circled in the related images are part of that blacklist.

![blacklist and sidebar](https://github.com/user-attachments/assets/b3154695-a0ff-464a-953b-c72a48e01404)

As per the screenshot I just stuck "anime girl" in as my query. My blocklist is custom but derived originally from Hamous' AI content blacklist which is found at https://github.com/HamousOnWheels/ublacklist-ai-slop .

**Comment by iorate** [comment]
fixed by #523
