### ISSUE TITLE
It looks like title/regex/ isn't compatible with brackets [] properly.

### ISSUE THREAD

**Issue by aoc272** [iorate/ublacklist#527]
![image](https://github.com/user-attachments/assets/10f01187-5ff1-4e93-80b5-ae4f5a4cbb04)

## Expected Behavior

it should block all webpage whose title has any of unicode characters ranging from u+0000 to u+ffff. (the range itself has no special meaning)

## Actual Behavior

syntax error

- Browser: Firefox 129
- Other extensions/add-ons: Tampermonkey, uBlockOrigin

**Comment by iorate** [comment]
Thank you for your report.
