### ISSUE TITLE
[Feature Request] support global.bing.com

### ISSUE THREAD

**Issue by KoishiMoe** [iorate/ublacklist#528]
Currently, this extension only supports Bing's main site (www.bing.com) and the China site (cn.bing.com). However in some regions, `global.bing.com` may need to be used for better search results. So I suggest adding it to the Bing match list to avoid unnecessary forks.

**Comment by acolasialiuliu** [comment]
When I enabled Bing, I was prompted to obtain access data for three domain names, none of which had cn.bing
