### ISSUE TITLE
Softsonic and uptodown and similer sites won't get blocked!

### ISSUE THREAD

**Issue by Alex-Mirov** [iorate/uBlacklist#55]
Hello

Those sites appears like these on google search:

*://the-tree-team-hide-app.en.uptodown.com/*
*://hide-apps-and-lock-apps.en.softonic.com/*
*://hidden-android-settings.en.softonic.com/*
*://applock-and-hide.en.softonic.com/*
*://gimp.en.uptodown.com/*

It also has the same issue with other searches that addon support,
the main sites gets blocked but not these links!

Sincerely
Alex

**Comment by iorate** [comment]
Use match patterns such as `*://*.uptodown.com/*` and `*://*.softonic.com/*`.

![uptodown](https://user-images.githubusercontent.com/682043/93016191-45ce5280-f5fa-11ea-8c88-4d9f315174b1.png)

**Comment by Alex-Mirov** [comment]
Hello

Many thanks for the solution, your addon is the best!

Sincerely
Alex



Sent from my Samsung Galaxy smartphone.



-------- Original message --------
