### ISSUE TITLE
Not working for Google mobile search page

### ISSUE THREAD

**Issue by tasy5kg** [iorate/uBlacklist#58]
Search anything on Google with Android mobile phone via any browser that supports Chrome extensions (For example, `Kiwi browser` based on Chromium or `FireFox`), the search result page looks having not `Block` button.

![FireShot Capture 008 - uBlacklist - Google Search - www google com](https://user-images.githubusercontent.com/30869777/93558289-b507c600-f9af-11ea-83b7-814003e9a0a4.png)

## Specifications

  - OS: Android 10
  - Browser: Wiki Browser (Or other Browsers that support extensions on Android)
  - Other extensions that might interfere: None

**Comment by iorate** [comment]
It is "won't fix" because Chrome extensions on mobile are not officially supported and probably will never.

Workarounds:
- use Firefox for Android (<=68), or 
- use a Chrome extension that can change your user agent to Firefox for Android.
