### ISSUE TITLE
[Feature Request] support timely refresh the filtering

### ISSUE THREAD

**Issue by e-cloud** [iorate/uBlacklist#59]
Hi,
I want to use https://greasyfork.org/en/scripts/375575-endless-google or this one https://chrome.google.com/webstore/detail/infinite-scroll-for-googl/acjdmkdcbbhokaleofmalpcnnkpgphpb,

However, those tools can work but not cooperate with uBlacklist properly. Seems uBlacklist just does the filtering once.

**Comment by iorate** [comment]
I'm not going to support all other extensions/userscripts that modify Google search result pages, although pull requests are welcome.

If you like, AutoPagerize and its derivatives are good alternatives that work with uBlacklist.
uAutoPagerize
https://chrome.google.com/webstore/detail/uautopagerize/kdplapeciagkkjoignnkfpbfkebcfbpb
