### ISSUE TITLE
DuckDuckGo inlined ad results are not completely removed from the search listing

### ISSUE THREAD

**Issue by GrayedFox** [iorate/uBlacklist#64]
## Expected Behavior
Blocked results should be completely invisible, including any child links or advertisements

## Actual Behavior
A paid DuckDuckGo result that has child links will have the main entry removed however the child links will remain visible.

## Steps to Reproduce the Problem

  1. block an DuckDuckGo advertisement result manually (block this page will not appear directly on result)
  1. refresh the page
  1. observe

## GIF

![ublacklist-bug-duckduck](https://user-images.githubusercontent.com/6493307/97082716-04bf5a00-160c-11eb-96b0-f5bc4a6ae205.gif)

**Comment by iorate** [comment]
Thank you for your report.
I have pushed a workaround for it.
