### ISSUE TITLE
The extension does not take effect in the second page of search results

### ISSUE THREAD

**Issue by n78** [iorate/uBlacklist#65]
## Expected Behavior
Block the site

## Actual Behavior
the site not blocking and Block button is not displayed

## Steps to Reproduce the Problem

  1.Install AC-Baidu([Github](https://github.com/langren1353/GM_script) or [GreasyFork](https://greasyfork.org/en/scripts/14178))in Tampermonkey
  2.Search a keyword in Google,click "CUSTOM" in the top-right corner,open "Auto Pager" and save
  3.

## Specifications

  - OS:Windows 10 64-bit
  - Browser:Chrome Stable 86.0.4240.183 (64-bit)
  - Other extensions that might interfere:-

**Comment by iorate** [comment]
Related to #59 

I'm not going to support all other extensions/userscripts that modify Google search result pages, although pull requests are welcome.
