### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by Darktowertr** [iorate/uBlacklist#68]
Could you bring dark mode support for the extension setting page? 
And how can we help you translate the extension to a specific language?

**Comment by iorate** [comment]
@Darktowertr 

> Could you bring dark mode support for the extension setting page?

Dark mode is added in v4.5.0.

> And how can we help you translate the extension to a specific language?

Please see the [readme](https://github.com/iorate/uBlacklist#locale).
