### ISSUE TITLE
Performance: Crashes after import a large number of sites

### ISSUE THREAD

**Issue by sstruct** [iorate/uBlacklist#7]
When I try to import a blocklist which contains lots of sites, the extension will be very slow and crash on every page.

* Reproduce
  *  import [blocklist](https://github.com/ligyxy/Blocklist)
  * google search for anything, then it will crash

**Comment by iorate** [comment]
I have just uploaded a new version (v2.2.0) to Chrome Web Store. Does it fix the problem?

**Comment by sstruct** [comment]
@iorate It works perfectly! Thanks!
