### ISSUE TITLE
Firefox page rendering issue

### ISSUE THREAD

**Issue by anonimuos** [iorate/uBlacklist#74]
In Chrome no problems but in Firefox, the page renders like this: (Attached)

![image](https://user-images.githubusercontent.com/46422834/104544495-e76bbc00-564d-11eb-8996-84dbf88bcde9.png)

Can you fix the "Block this site" text please to render correctly?

**Comment by group-leafy** [comment]
I can't reproduce the problem. (Macos 11.1, Firefox 84.0.2, uBlacklist 4.7.2)

What is your environment?

**Comment by HoneyLuka** [comment]
I can't reproduce the problem. (Macos 11.1, Firefox 84.0.2, uBlacklist 4.7.2)

What is your environment?

**Comment by anonimuos** [comment]
Oh ok found that it is an incompatibility with a userscript that restores Google search results' hyperlinks to how they used to be:
https://greasyfork.org/scripts/411886-better-google-updated

Windows 10, Firefox 84.0.2 64-bit, uBlacklist 4.7.2.

**Comment by group-leafy** [comment]
I'm not sure if it still works when multiple plugins modify the page at the same time.

I don't know if there is a way to determine the order of plugin execution? If can't, the issue may not be fixed.

Sorry I'm not a web developer. So my suggestion is to disable that script temporarily and waiting for response from the developer.

**Comment by HoneyLuka** [comment]
I'm not sure if it still works when multiple plugins modify the page at the same time.

I don't know if there is a way to determine the order of plugin execution? If can't, the issue may not be fixed.

Sorry I'm not a web developer. So my suggestion is to disable that script temporarily and waiting for response from the developer.

**Comment by iorate** [comment]
Insert the following code in the right place of Better Google

```javascript
style.sheet.insertRule('.ub-button { word-break: normal; }');
```

**Comment by anonimuos** [comment]
Thank you. Incidentally, Better Google script broke today and stopped working (probably Google made some changes again).
