### ISSUE TITLE
Version 4.4.0 after doesn't work on Firefox 56.0.2

### ISSUE THREAD

**Issue by tadusaman8** [iorate/uBlacklist#75]
## Expected Behavior
If I click 'setting' button on addons manager (about:addons) of firefox, the setting mode appears.

## Actual Behavior
Even if I click 'setting' button on addons manager (about:addons) of firefox, the setting mode does not appear (blank page).

## Steps to Reproduce the Problem

like this pic
https://i.imgur.com/nIilJMH.png

## Specifications

- OS: Windows 10  64bit  (also the same on Windows 7 64bit)
- Browser:Firefox 56.0.2
- Other extensions that might interfere: None

**Comment by iorate** [comment]
Why do you use Firefox 56, which is no longer supported by Mozilla?

If you want to use uBlacklist along with legacy add-ons, you can use [Waterfox Classic](https://www.waterfox.net/) (not "Third Generation") setting `dom.webcomponents.enabled` to `true` in `about:config`.

**Comment by tadusaman8** [comment]
Thank you for your reply.
I think you're Japanese. I'm too, so Can I talk with Japanese ?


     ----- Original Message -----
