### ISSUE TITLE
Synchronize options other than block rules

### ISSUE THREAD

**Issue by eighttails** [iorate/uBlacklist#76]
## Expected Behavior
I subscribe blacklist from
https://raw.githubusercontent.com/arosh/ublacklist-stackoverflow-translation/master/uBlacklist.txt
Please sync subscribe list in the same way as blacklist in setting's General section.

## Actual Behavior
Subscription list is not synced so I have to add subscription URL to every running browsers.

## Steps to Reproduce the Problem

1. Add subsctiption URL to the addon.
1. Enable sync.
1. Open the addon settings in another machine.
1. Enable sync.
1. See if blacklist is working.(Actually not.) 

## Specifications

- OS:Windows 10 64bit
- Browser:Firefox
- Other extensions that might interfere:

**Comment by iorate** [comment]
TODO: The sync feature should be redesigned to sync the setting items other than 'blacklist'.
