### ISSUE TITLE
Firefox support?

### ISSUE THREAD

**Issue by jostyee** [iorate/uBlacklist#8]
I'm looking for a better replacement for the userscript https://greasyfork.org/en/scripts/1682-google-hit-hider-by-domain-search-filter-block-sites , hope this project can offer an addon for Firefox user.

**Comment by iorate** [comment]
There is actually a Firefox version.
https://addons.mozilla.org/en-US/firefox/addon/ublacklist/
https://github.com/iorate/uBlacklist/tree/firefox

I will add the link to README.md.
