### ISSUE TITLE
How to keep the settings permanent/from being changed?

### ISSUE THREAD

**Issue by ThrowThrowThrowAway98** [iorate/uBlacklist#80]
Hello, I've never used GitHub, so I don't know if I'm using this properly, but I can't seem to find this anywhere else. Is it possible for the settings/configurations in the blocklist from being changed? Let's say that I placed YouTube in the blocklist, is it possible for that block of YouTube to be unchangeable (Can't be removed)? I've looked at the group policy editor, but I don't know if there's an option to keep extension settings from being changed.

**Comment by iorate** [comment]
I think it is impossible.
