### ISSUE TITLE
I want the ability to block with one click on the main domain, including subdomains.

### ISSUE THREAD

**Issue by Misaki0331** [iorate/uBlacklist#83]
Hello. I have a suggestion.
Currently, I block, the following URL will be registered. 
【＊://123456abcd.example.com/＊】

But I want to register like this.
【＊://＊.example.com/＊】
The asterisk is replaced with another character because the GitHub specification.

I would like you to add "Block the main domain" to the block display. 
Thank you.

**Comment by iorate** [comment]
Won't fix; it is difficult to find "main" domains in a consistent and intuitive manner. What is the "main" domain of `gist.github.com`? How about `library.city.chuo.tokyo.jp`?

By the way, you can escape asterisks.
`\*://123456abcd.example.com/\*` -> \*://123456abcd.example.com/\*
