### ISSUE TITLE
Improve support for kiwi browser (Android browser)

### ISSUE THREAD

**Issue by werererer** [iorate/uBlacklist#85]
There is the kiwi browser (an android browser) which supports chrome extensions. But this extension doesn't work properly there: / 
- Sites still show up after blocking them if I am on the mobile version of google, but when I switch to the desktop version it works. 
- opening the settings shows just a blank screen

**Comment by iorate** [comment]
ref: #58 
Chromium-based browsers for Android are not supported, although PRs are welcome.
