### ISSUE TITLE
Please support extensions which load more search results after scrolling.

### ISSUE THREAD

**Issue by Rtizer-9** [iorate/uBlacklist#86]
I'm using this extension called `Google auto-load` [https://addons.mozilla.org/en-GB/firefox/addon/google-auto-load/](url) which loads more search results on scrolling just like Duckduckgo without clicks. There are several other extensions like these.

It would be great if ublacklist can support the results which are loaded after scrolling.

Thanks

**Comment by iorate** [comment]
Related to #59, #65

I'm not going to support all other extensions/userscripts that modify Google search result pages, although pull requests are welcome.
My recommendation is [weAutoPagerize](https://addons.mozilla.org/en-US/firefox/addon/weautopagerize/). It works great with uBlacklist.
