### ISSUE TITLE
where can i edit all rules ?

### ISSUE THREAD

**Issue by Ehco1996** [iorate/uBlacklist#9]
it's so nice of your make this chrome ext ! thanks!

---

i want to cancel some block rule ,but i can't find right place 

please help me out

**Comment by iorate** [comment]
You can edit block rules on the option page.
To open the option page, right-click the toolbar icon and select "Options" (Chrome) or "Manage Extension" (Firefox).

**Comment by Ehco1996** [comment]
oh, i found it ,thanks!
