### ISSUE TITLE
Add Yahoo! Japan support

### ISSUE THREAD

**Issue by munierujp** [iorate/uBlacklist#90]
For Japanese users, [Yahoo! Japan](https://search.yahoo.co.jp/) is the second most popular search service and its share is 21.24%.[^1]

[^1]: https://gs.statcounter.com/search-engine-market-share/all/japan/

**Comment by iorate** [comment]
@munierujp yes you can!

**Comment by helmetplumeggbanana** [comment]
Shouldn't the issue title be renamed from Yahoo to Yahoo Japan?
Yahoo in Japan is unique and different from the rest of the world.

**Comment by munierujp** [comment]
@helmetplumeggbanana That's right. I have done.
