### ISSUE TITLE
Add Yandex Support

### ISSUE THREAD

**Issue by RedWavez** [iorate/uBlacklist#91]
I really like to use this extension to block numerous websites I don't like. But I miss it on Yandex. I often use Yandex whenever I don't find what I need with Google, but there is so much spam and that difficults my searches. Can you try to implement this feature? Thank you.

**Comment by Kristinita** [comment]
The proposal to include Yandex isn’t just someone’s personal wish. As of December 1, 2021, Yandex is in [**8th place in the list of the most visited websites in the world**](https://www.similarweb.com/ru/top-websites/) and it [**the most visited site in my country**](https://www.similarweb.com/ru/top-websites/russian-federation/).

I hope Yandex will be added to the list of search engines supported by uBlacklist, how it's done in Google Hit Hider by Domain.

Thanks.
