### ISSUE TITLE
Does not filter google's highlighted results

### ISSUE THREAD

**Issue by byron-hawkins** [iorate/uBlacklist#96]
## Expected Behavior

With a blocklist containing `*://en.cppreference.com/*`, the search `std::vector` should not show any results from `cppreference.com`, even if the result is in a special highlight format generated by google.

## Actual Behavior

With a blocklist containing `*://en.cppreference.com/*`, the search `std::vector` shows a highlighted first result of `https://en.cppreference.com › cpp › container › vector`. In the main list of results, `cppreference.com` is correctly blocked (no such results appear). So the plugin is not filtering highlighted results.

## Steps to Reproduce the Problem

1. block `*://en.cppreference.com/*`
1. search for `std::vector`

## Specifications

- OS: Fedora 34
- Browser: FireFox 88.0.1
- Other extensions that might interfere:

**Comment by mpc2008cn** [comment]
It appears on iOS ublacklist for safari too.
version: 6.13.0
![image](https://user-images.githubusercontent.com/11917818/145933302-c2663b60-9965-4459-9549-87a799933a85.png)
![image](https://user-images.githubusercontent.com/11917818/145933336-aad9a7ca-221e-431f-90cb-05be1dfbe9b2.png)
