### ISSUE TITLE
NetworkError during sync

### ISSUE THREAD

**Issue by byron-hawkins** [iorate/uBlacklist#97]
## Expected Behavior

Sync should work correctly because my google drive credentials have not changed and the network is not having any problems.

## Actual Behavior

Sync shows `Error: NetworkError when attempting to fetch resource.` No, there is no network error. You have some other error.

## Specifications

- OS: Fedora 34
- Browser: Firefox 88.0.1
- Other extensions that might interfere:

**Comment by iorate** [comment]
@byron-hawkins 
I cannot reproduce the problem with Firefox 89 on Windows 10.
Does it occur with a brand-new profile?

**Comment by byron-hawkins** [comment]
Sorry, I can't really create a fresh profile without completely destroying my entire browser configuration, which represents many hours of effort, much of which is not integrated into any export/import feature.

**Comment by iorate** [comment]
Could you create a new profile in `about:profiles`, install this extension and enable sync? It doesn't destroy your existing profiles.

**Comment by byron-hawkins** [comment]
Sure, well I'm trying to do this now, but when I go to sync, it asks where to sync. There is only my one google drive, which is already synced to uBlacklist in my main firefox profile. So if I also sync the test to the same google drive, what happens? And if I sync the test somewhere else, then it's not a test of the target scenario anymore, it's some other scenario that has nothing to do with this bug. So what can I do here?

**Comment by iorate** [comment]
>  So if I also sync the test to the same google drive, what happens?

The blocklist used in the original profile will be downloaded to the new profile via your Google Drive. (NOTE: If you update the blocklist in the new profile BEFORE enabling sync, it will overwrite your existing blocklist.)

> So what can I do here?

1. clarify the condition under which the problem is reproduced; does it happen with a new profile of Firefox on Fedora?
2. tell me the detail of the error, which may be displayed in  `about:devtools-toolbox?id=%40ublacklist&type=extension` > `Console` or `Network`.

**Comment by byron-hawkins** [comment]
It does indeed function correctly in the test profile. My blocklist is downloaded, though it is not current because of course the main profile has not been able to sync in a long time. I tried restarting the browser in each profile and nothing changed: it works in the test profile, but not in my main profile.

**Comment by iorate** [comment]
Did you try re-installing the extension in your main profile?
(You may need to export your blocklist before it)

> tell me the detail of the error, which may be displayed in about:devtools-toolbox?id=%40ublacklist&type=extension > Console or Network.

What about this?

**Comment by byron-hawkins** [comment]
Well, the error doesn't occur today, so I can't investigate. This is good though, the sync works! If the error happens again later, I'll try to check the log.

**Comment by iorate** [comment]
If you run into the problem again, please feel free to comment on this issue.
