### ISSUE TITLE
Add support for Safari on iOS

### ISSUE THREAD

**Issue by iorate** [iorate/uBlacklist#99]
Update (Sep 25, 2022)

uBlacklist is now available on iOS/iPadOS 15 thanks to @HoneyLuka !
https://apps.apple.com/us/app/ublacklist-for-safari/id1547912640

TODO:
- [x] image search
- [x] news search
- [x] video search

---

Apple has announced that iOS 15 will support Safari Web Extensions.
https://developer.apple.com/videos/play/wwdc2021/10104/

Thanks to @HoneyLuka, uBlacklist is already available as a Safari Web Extension on macOS.
I'd like to add support for Safari on iOS because I'm an iPhone and iPad user.

**Comment by HoneyLuka** [comment]
Thanks for your contribution. Can't wait to use it. :)

**Comment by HoneyLuka** [comment]
And if you need to get control of the macOS app for some reason, please let me know and I will transfer it to you any time. 🙏

**Comment by iorate** [comment]
@HoneyLuka 
Thanks, but for now I don't need control of the macOS app.

I will contact you here when I implement support for Safari on iOS 15.

**Comment by iorate** [comment]
iOS/iPadOS 15 will be released on Sep 20!
https://www.apple.com/ios/ios-15/

I pushed a commit (9299d4569f9ff789b5fd91844417288114ed976a) which added initial support for Safari 15 on iOS.
Although it supports only simple results in the "All" search, it seems to work well on iOS simulator:

<img src="https://user-images.githubusercontent.com/682043/133468647-08eb537b-2445-4560-8307-2109456b7907.png" width="320px" alt="Google Search on iOS Simulator"> <img src="https://user-images.githubusercontent.com/682043/133468665-55cbdc9f-de8c-4bef-917c-39b156871681.png" width="320px" alt="The options page on iOS Simulator">

I will add support for more types of search results later.

@HoneyLuka Could you please publish "uBlacklist for Safari" for iOS/iPadOS after iOS/iPadOS 15 are released and you think this extension supports them sufficiently?

**Comment by HoneyLuka** [comment]
@iorate Thanks for your work🎉, I think it's fine for a first release on iOS. I am now starting to work on the iOS version release preparation

**Comment by iorate** [comment]
@HoneyLuka Thank you. I'm looking forward to it.

**Comment by iorate** [comment]
The build system was upgraded for faster builds using esbuild-loader.
To generate a production build for Safari:

```diff
# Install dependencies
- yarn install --frozen-lockfile
+ yarn install --immutable

# Build
- yarn build:safari:production
+ yarn build safari production
```

cc: @HoneyLuka

**Comment by HoneyLuka** [comment]
@iorate Thank you for the tips. I will use it tomorrow.

iOS version almost done. When I finished, I will tell you here.

**Comment by HoneyLuka** [comment]
@iorate When I debug on iPad, I found an UI issue.
![bug](https://user-images.githubusercontent.com/4635725/133918118-470c4150-243a-422b-8fc0-1de1b18d413c.png)

**Comment by iorate** [comment]
@HoneyLuka Thank you for reporting an issue. Does the latest commit (017bf78642bae9f3b0146fe29ef12822763ddaf3) fix the problem?

![ipad-popup](https://user-images.githubusercontent.com/682043/133925327-1aa02ddc-568c-4860-863a-20042a53f535.png)

**Comment by HoneyLuka** [comment]
@iorate I merged your master branch, It's OK👍

**Comment by iorate** [comment]
@HoneyLuka I'm glad to hear that.

I would appreciate if you could also check the sync feature that I added a bit before (3fb12571fd9aa7e3ed464b4b3408105922c852d1). Because Safari on iOS lacks some APIs, users need to copy authorization codes from [iorate.github.io](https://iorate.github.io/ublacklist/callback?code=example) manually.

<p>
<img src="https://user-images.githubusercontent.com/682043/133925747-98954ad0-3d5b-43c1-a83e-92e67ada60f3.png" width="240px">
<img src="https://user-images.githubusercontent.com/682043/133925748-3f988ad3-0ada-47ef-9b0c-8732de97aac3.png" width="240px">
<img src="https://user-images.githubusercontent.com/682043/133925750-90f0fa0f-bdfd-4fe2-bd15-96a7e3e6084c.png" width="240px">
</p?

**Comment by HoneyLuka** [comment]
@iorate ok, I will try it later, if any questions I will report to you.

**Comment by HoneyLuka** [comment]
@iorate I create a test dropbox app, set it's callback url to  ```iorate.github.io```.  

Most functions are working. Only a little problem: 

After sync finished, **Appearance**, **Subscription** module do not refresh automatically. Rules textarea show a tips 'updated Reload'. Maybe reload the whole options page automatically after sync?

**Comment by iorate** [comment]
@HoneyLuka Thank you for your feedback.

> Maybe reload the whole options page automatically after sync?

I don't like automatic reload so much, so added a manual-reload button.
(The screenshot below is taken in Firefox on Windows)

![reload](https://user-images.githubusercontent.com/682043/133930420-f4e8b259-a8c7-4e74-8aeb-6a5d4f59c624.png)

**Comment by HoneyLuka** [comment]
@iorate I have completed the development of the iOS version, and ready for app store review, the first version is reviewing for external test(TestFlight External Test).

<img width="1389" alt="screenshot" src="https://user-images.githubusercontent.com/4635725/133989774-54685103-5bab-44ea-91ee-99b0d4da1cc3.png">

If you want to build yourself, you can [get code from my branch](https://github.com/HoneyLuka/uBlacklist/tree/safari-port/safari-project).

Should I submit the current release to app store or waiting for your next tag and rebuild a new release ?

**Comment by iorate** [comment]
@HoneyLuka Great!

Would you please bulid the current `master` (just marked as `v6.4.0`) and submit it as v6.4.0?

(As a side note, v6.4.0 will not be released for Chrome & Firefox. v6.3.6 is still under review by Chrome Web Store...)

**Comment by HoneyLuka** [comment]
@iorate ok, I will rebuild as 6.4.0 later.

**Comment by iorate** [comment]
I added v6.4.1 (and perhaps will add more) because v6.3.6 is rejected by Chrome Web Store.
This does not affect the Safari version.

**Comment by CyshallChan** [comment]
@HoneyLuka 🤣已经在等了。

**Comment by HoneyLuka** [comment]
> @HoneyLuka 🤣已经在等了。

Welcome to be the first user of iOS version🎉

**Comment by HoneyLuka** [comment]
@iorate @CyshallChan iOS version is online🎉

**Comment by CyshallChan** [comment]
@iorate @HoneyLuka Already used, thank you two very much.

**Comment by iorate** [comment]
@HoneyLuka
I installed "uBlacklist for Safari" to iOS 15 (on iPhone 11 Pro) and iPadOS 15 (on iPad Pro 12.9-inch)
and confirmed it worked well.
Thank you for your excellent work!

**Comment by iorate** [comment]
We should add support for:
- [ ] image search
- [ ] news search
- [ ] video search

**Comment by iorate** [comment]
Synchronization and subscription updates may not occur regularly. In such cases, the alarms are certainly set, but Safari does not fire them.

<img width="1000" alt="alarm" src="https://user-images.githubusercontent.com/682043/134344139-03c6f00e-5294-448d-9000-3aa22b4f6b81.png">

(18 hours behind!)

I'm not sure what the reproduction conditions are.

**Comment by HoneyLuka** [comment]
@iorate
Does this bug appear when the Safari app is in the background? 
Usually in native app of iOS, when the app switches to the background, OS give app a short time to execute code. After that the app will become **background/sleep** state, can't execute code, and **Timer** also can't fire(suspend).
When the app active again, the timer will be resume.

I think this bug is very similar to native app. Because Safari is also a native app, when it is in the background, the activity of the extension is suspended due to battery life considerations

**Comment by iorate** [comment]
@HoneyLuka 
I think it is reasonable that alarms are not fired when Safari is in background, but alarms should be resumed after Safari is back to foreground as you say.

However, I have met some different situations:
- Sync (every 15 minutes) and subscription (every 2 hours) did not occur after moving Safari from background for several hours to foreground
- Sync (every 15 minutes) and subscription (every 2 hours) occurred immediately after moving Safari from background for several hours to foreground
- Sync (every 15 minutes) occurred but subscription (every 2 hours) did not occur after moving Safari from background for several hours to foreground
- Sync (every 5 minites) and subscription (every 5 minutes) did not occur even when I keep Safari in foreground during the interval

I don't understand the behavior of Safari...

**Comment by HoneyLuka** [comment]
@iorate
This may be a bug in Safari, which is not surprising.

If this is indeed a bug, I'm thinking of a solution.
I'm not good at web development. I'm not sure if there is a way to let the extension know about Safari state changes. After a short search, I found an event [**windows.onFocusChanged**](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows). Maybe when Safari become active, this event will be callback. The document said this works after Safari 14 (maybe it's macOS Safari 14).
If it is indeed, in unfocus event remove all alarms, and in focus event recreate them (More complex logic can also be added, for example fire an update immediately or based on last fire time). 

Summary Steps:
1. Check if **windows.onFocusChanged** is Working properly.
2. Check recreated alarm is Working properly. (If this bug is more critical, the recreated alarm maybe also does not work properly)
3. If both is ok, write code on event callback.

**Comment by iorate** [comment]
@HoneyLuka 
Sounds good.
`windows.onFocusChanged` seems to work in iOS Simulator.

**Comment by iorate** [comment]
I've been trying the `windows.onFocusChanged` hack since last night on my iPhone and iPad.
So far, it seems to be working.

**Comment by HoneyLuka** [comment]
@iorate Glad it works. Thank your for your hard work.

**Comment by iorate** [comment]
I believe it works.
@HoneyLuka Would you please publish v6.6.0 when it's convenient for you?

**Comment by HoneyLuka** [comment]
@iorate Thank you🎉, I will submit it to app store right now.

**Comment by HoneyLuka** [comment]
iOS 6.6.0 is online now.

**Comment by iorate** [comment]
@HoneyLuka 
It works well on my actual devices. Thanks!

**Comment by love4taylor** [comment]
Is it possible to use CloudKit to synchronize data?

**Comment by HoneyLuka** [comment]
> Is it possible to use CloudKit to synchronize data?

I haven't look this part yet. Usually Apple's services are only available on Apple devices. 
Even it is possible, I don't think it's necessary to do this right now.
There is a lot of work to do for this feature.

**Comment by iorate** [comment]
Image, news and video search support is available in v6.7.0. cc: @HoneyLuka

**Comment by iorate** [comment]
@HoneyLuka The screenshots and captions seem to mismatch in the iPad app.

![ipad-screenshot](https://user-images.githubusercontent.com/682043/135752698-b03a089d-bf3a-4d12-aa44-f341c1499078.png)

**Comment by HoneyLuka** [comment]
> @HoneyLuka The screenshots and captions seem to mismatch in the iPad app.
> 
> 
> 
> ![ipad-screenshot](https://user-images.githubusercontent.com/682043/135752698-b03a089d-bf3a-4d12-aa44-f341c1499078.png)
> 
> 

It seems a bug, I will fix it later and release 6.7.0

**Comment by HoneyLuka** [comment]
iOS 6.7.0 is online🎉

**Comment by iorate** [comment]
@HoneyLuka thanks!

**Comment by iorate** [comment]
I'm closing this issue because I think basic support for iOS is already done.
For further problems on iOS, please create individual issues for each problem.
